CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113165331_InitialCreation') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'tanatos') THEN
            CREATE SCHEMA tanatos;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113165331_InitialCreation') THEN
    CREATE TABLE tanatos.tipo_receptor_notificacion (
        id bigint NOT NULL,
        nombre text NOT NULL,
        vigente boolean NOT NULL,
        CONSTRAINT "PK_tipo_receptor_notificacion" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113165331_InitialCreation') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251113165331_InitialCreation', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    ALTER TABLE tanatos.tipo_receptor_notificacion DROP COLUMN vigente;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    COMMENT ON TABLE tanatos.tipo_receptor_notificacion IS 'Tabla que contiene los tipos de receptores de notificación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    COMMENT ON COLUMN tanatos.tipo_receptor_notificacion.nombre IS 'Nombre del tipo de receptor de notificación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    COMMENT ON COLUMN tanatos.tipo_receptor_notificacion.id IS 'Identificador del tipo de receptor de notificación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    ALTER TABLE tanatos.tipo_receptor_notificacion ADD vigencia boolean NOT NULL DEFAULT FALSE;
    COMMENT ON COLUMN tanatos.tipo_receptor_notificacion.vigencia IS 'Vigencia del tipo de receptor de notificación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE TABLE tanatos.categoria_norma (
        id bigint NOT NULL,
        nombre text NOT NULL,
        nombre_corto text,
        descripcion text,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_categoria_norma" PRIMARY KEY (id)
    );
    COMMENT ON TABLE tanatos.categoria_norma IS 'Tabla que contiene las categorías de las normas';
    COMMENT ON COLUMN tanatos.categoria_norma.id IS 'Identificador de la categoría.';
    COMMENT ON COLUMN tanatos.categoria_norma.nombre IS 'Nombre de la categoría.';
    COMMENT ON COLUMN tanatos.categoria_norma.nombre_corto IS 'Nombre corto de la categoría.';
    COMMENT ON COLUMN tanatos.categoria_norma.descripcion IS 'Descripción de la categoría.';
    COMMENT ON COLUMN tanatos.categoria_norma.vigencia IS 'Vigencia de la categoría.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE TABLE tanatos.destinatario_notificacion (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        sub text NOT NULL,
        id_tipo_receptor bigint NOT NULL,
        destino text NOT NULL,
        codigo_validacion text NOT NULL,
        intentos_validacion smallint NOT NULL,
        validado boolean NOT NULL,
        fecha_creacion timestamp with time zone NOT NULL,
        fecha_eliminacion timestamp with time zone NOT NULL,
        vigente boolean NOT NULL,
        CONSTRAINT "PK_destinatario_notificacion" PRIMARY KEY (id),
        CONSTRAINT "FK_destinatario_notificacion_tipo_receptor_notificacion_id_tip~" FOREIGN KEY (id_tipo_receptor) REFERENCES tanatos.tipo_receptor_notificacion (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.destinatario_notificacion IS 'Tabla que contiene los destinatarios de las notificaciones de un usuario.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.id IS 'Identificador del destinatario de notificación.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.sub IS 'Usuario al que pertenece el destinatario de notificación.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.id_tipo_receptor IS 'Identificador del tipo de receptor asociado al destinatario.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.destino IS 'Destino de la notificación. Puede ser un correo o un número de Whatsapp.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.codigo_validacion IS 'Código generado para validar que el destinatario se suscribe a la notificación.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.intentos_validacion IS 'Cantidad de intentos de validar al destinatario.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.validado IS 'Identifica si el destinatario ya fue validado.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.fecha_creacion IS 'Fecha en que se creó el destinatario.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.fecha_eliminacion IS 'Fecha en que se eliminó el destinatario.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.vigente IS 'Vigencia del destinatario.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE TABLE tanatos.tipo_fiscalizador (
        id bigint NOT NULL,
        nombre text NOT NULL,
        nombre_corto text,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_tipo_fiscalizador" PRIMARY KEY (id)
    );
    COMMENT ON TABLE tanatos.tipo_fiscalizador IS 'Tabla que contiene los tipos de fiscalizadores de las normas.';
    COMMENT ON COLUMN tanatos.tipo_fiscalizador.id IS 'Identificador del tipo de fiscalizador.';
    COMMENT ON COLUMN tanatos.tipo_fiscalizador.nombre IS 'Nombre del tipo de fiscalizador.';
    COMMENT ON COLUMN tanatos.tipo_fiscalizador.nombre_corto IS 'Nombre corto del tipo de fiscalizador.';
    COMMENT ON COLUMN tanatos.tipo_fiscalizador.vigencia IS 'Vigencia del tipo de fiscalizador.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE TABLE tanatos.tipo_periodicidad (
        id bigint NOT NULL,
        nombre text NOT NULL,
        descripcion text,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_tipo_periodicidad" PRIMARY KEY (id)
    );
    COMMENT ON TABLE tanatos.tipo_periodicidad IS 'Tabla que contiene los tipos de periodicidad.';
    COMMENT ON COLUMN tanatos.tipo_periodicidad.id IS 'Identificador del tipo de periodicidad.';
    COMMENT ON COLUMN tanatos.tipo_periodicidad.nombre IS 'Nombre del tipo de periodicidad.';
    COMMENT ON COLUMN tanatos.tipo_periodicidad.descripcion IS 'Descripción del tipo de periodicidad.';
    COMMENT ON COLUMN tanatos.tipo_periodicidad.vigencia IS 'Vigencia del tipo de periodicidad.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE TABLE tanatos.tipo_unidad_tiempo (
        id bigint NOT NULL,
        nombre text NOT NULL,
        cant_segundos bigint NOT NULL,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_tipo_unidad_tiempo" PRIMARY KEY (id)
    );
    COMMENT ON TABLE tanatos.tipo_unidad_tiempo IS 'Tabla que contiene los tipos de unidades de tiempo.';
    COMMENT ON COLUMN tanatos.tipo_unidad_tiempo.id IS 'Identificador del tipo de unidad de tiempo.';
    COMMENT ON COLUMN tanatos.tipo_unidad_tiempo.nombre IS 'Nombre del tipo de unidad de tiempo.';
    COMMENT ON COLUMN tanatos.tipo_unidad_tiempo.cant_segundos IS 'Cantidad de segundos que representan a la unidad de tiempo.';
    COMMENT ON COLUMN tanatos.tipo_unidad_tiempo.vigencia IS 'Vigencia del tipo de unidad de tiempo.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE INDEX "IX_destinatario_notificacion_id_tipo_receptor" ON tanatos.destinatario_notificacion (id_tipo_receptor);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE INDEX "IX_destinatario_notificacion_sub_id_tipo_receptor" ON tanatos.destinatario_notificacion (sub, id_tipo_receptor);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251117132506_TablasTipo', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE TABLE tanatos.template (
        id bigint NOT NULL,
        id_template_padre bigint,
        nombre text NOT NULL,
        descripcion text NOT NULL,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_template" PRIMARY KEY (id),
        CONSTRAINT "FK_template_template_id_template_padre" FOREIGN KEY (id_template_padre) REFERENCES tanatos.template (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.template IS 'Tabla que contiene los templates de normas a inscribirse.';
    COMMENT ON COLUMN tanatos.template.id IS 'Identificador del template.';
    COMMENT ON COLUMN tanatos.template.id_template_padre IS 'Identificador del template padre.';
    COMMENT ON COLUMN tanatos.template.nombre IS 'Nombre del template.';
    COMMENT ON COLUMN tanatos.template.descripcion IS 'Descripcion del template.';
    COMMENT ON COLUMN tanatos.template.vigencia IS 'Vigencia del template.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE TABLE tanatos.inscripcion_template (
        sub text NOT NULL,
        id_template bigint NOT NULL,
        fecha_activacion timestamp with time zone NOT NULL,
        fecha_desactivacion timestamp with time zone,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_inscripcion_template" PRIMARY KEY (sub, id_template),
        CONSTRAINT "FK_inscripcion_template_template_id_template" FOREIGN KEY (id_template) REFERENCES tanatos.template (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.inscripcion_template IS 'Tabla que contiene los templates a los que un usuario está inscrito.';
    COMMENT ON COLUMN tanatos.inscripcion_template.sub IS 'Usuario al que está asociada la inscripción.';
    COMMENT ON COLUMN tanatos.inscripcion_template.id_template IS 'Identificador del template al que está inscrito el usuario.';
    COMMENT ON COLUMN tanatos.inscripcion_template.fecha_activacion IS 'Fecha en que se activa la inscripción.';
    COMMENT ON COLUMN tanatos.inscripcion_template.fecha_desactivacion IS 'Fecha en que se desactiva la inscripción.';
    COMMENT ON COLUMN tanatos.inscripcion_template.vigencia IS 'Vigencia de la inscripción.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE TABLE tanatos.template_norma (
        id bigint NOT NULL,
        id_template bigint NOT NULL,
        nombre text NOT NULL,
        descripcion text,
        id_tipo_periodicidad bigint,
        multa text,
        id_categoria_norma bigint NOT NULL,
        CONSTRAINT "PK_template_norma" PRIMARY KEY (id),
        CONSTRAINT "FK_template_norma_categoria_norma_id_categoria_norma" FOREIGN KEY (id_categoria_norma) REFERENCES tanatos.categoria_norma (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_template_norma_template_id_template" FOREIGN KEY (id_template) REFERENCES tanatos.template (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_template_norma_tipo_periodicidad_id_tipo_periodicidad" FOREIGN KEY (id_tipo_periodicidad) REFERENCES tanatos.tipo_periodicidad (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.template_norma IS 'Tabla que contiene las normas asociadas a un template.';
    COMMENT ON COLUMN tanatos.template_norma.id IS 'Identificador de la norma asociada al template.';
    COMMENT ON COLUMN tanatos.template_norma.id_template IS 'Identificador del template al que pertenece la norma.';
    COMMENT ON COLUMN tanatos.template_norma.nombre IS 'Nombre de la norma.';
    COMMENT ON COLUMN tanatos.template_norma.descripcion IS 'Descripcion de la norma.';
    COMMENT ON COLUMN tanatos.template_norma.id_tipo_periodicidad IS 'Identificador del tipo de periodicidad asociado a la norma.';
    COMMENT ON COLUMN tanatos.template_norma.multa IS 'Multa de no cumplir con la norma';
    COMMENT ON COLUMN tanatos.template_norma.id_categoria_norma IS 'Identificador de la categoría a la que pertenece la norma.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE TABLE tanatos.template_norma_fiscalizador (
        id_template_norma bigint NOT NULL,
        id_tipo_fiscalizador bigint NOT NULL,
        CONSTRAINT "PK_template_norma_fiscalizador" PRIMARY KEY (id_template_norma, id_tipo_fiscalizador),
        CONSTRAINT "FK_template_norma_fiscalizador_template_norma_id_template_norma" FOREIGN KEY (id_template_norma) REFERENCES tanatos.template_norma (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_template_norma_fiscalizador_tipo_fiscalizador_id_tipo_fisca~" FOREIGN KEY (id_tipo_fiscalizador) REFERENCES tanatos.tipo_fiscalizador (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.template_norma_fiscalizador IS 'Tabla que contiene la relación entre un template norma y un fiscalizador.';
    COMMENT ON COLUMN tanatos.template_norma_fiscalizador.id_template_norma IS 'Identificador de la norma perteneciente a un template.';
    COMMENT ON COLUMN tanatos.template_norma_fiscalizador.id_tipo_fiscalizador IS 'Identificador del tipo de fiscalizador.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE TABLE tanatos.template_norma_notificacion (
        id_template_norma bigint NOT NULL,
        id_tipo_unidad_tiempo_antelacion bigint NOT NULL,
        cant_antelacion integer NOT NULL,
        CONSTRAINT "PK_template_norma_notificacion" PRIMARY KEY (id_template_norma, id_tipo_unidad_tiempo_antelacion),
        CONSTRAINT "FK_template_norma_notificacion_template_norma_id_template_norma" FOREIGN KEY (id_template_norma) REFERENCES tanatos.template_norma (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_template_norma_notificacion_tipo_unidad_tiempo_id_tipo_unid~" FOREIGN KEY (id_tipo_unidad_tiempo_antelacion) REFERENCES tanatos.tipo_unidad_tiempo (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.template_norma_notificacion IS 'Tabla que contiene las notificaciones asociadas a una template norma.';
    COMMENT ON COLUMN tanatos.template_norma_notificacion.id_template_norma IS 'Identificador de la template norma.';
    COMMENT ON COLUMN tanatos.template_norma_notificacion.id_tipo_unidad_tiempo_antelacion IS 'Identificador del tipo de unidad de tiempo a usar para la notificación.';
    COMMENT ON COLUMN tanatos.template_norma_notificacion.cant_antelacion IS 'Cantidad de unidades de tiempo a usar para la notificación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_inscripcion_template_id_template" ON tanatos.inscripcion_template (id_template);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_template_id_template_padre" ON tanatos.template (id_template_padre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_template_norma_id_categoria_norma" ON tanatos.template_norma (id_categoria_norma);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_template_norma_id_template" ON tanatos.template_norma (id_template);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_template_norma_id_tipo_periodicidad" ON tanatos.template_norma (id_tipo_periodicidad);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_template_norma_fiscalizador_id_tipo_fiscalizador" ON tanatos.template_norma_fiscalizador (id_tipo_fiscalizador);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_template_norma_notificacion_id_tipo_unidad_tiempo_antelacion" ON tanatos.template_norma_notificacion (id_tipo_unidad_tiempo_antelacion);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251117144252_TablasTemplates', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205214630_CorreccionVigencia') THEN
    ALTER TABLE tanatos.destinatario_notificacion RENAME COLUMN vigente TO vigencia;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205214630_CorreccionVigencia') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251205214630_CorreccionVigencia', '9.0.11');
    END IF;
END $EF$;
COMMIT;

