CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113165331_InitialCreation') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'tanatos') THEN
            CREATE SCHEMA tanatos;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113165331_InitialCreation') THEN
    CREATE TABLE tanatos.tipo_receptor_notificacion (
        id bigint NOT NULL,
        nombre text NOT NULL,
        vigente boolean NOT NULL,
        CONSTRAINT "PK_tipo_receptor_notificacion" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113165331_InitialCreation') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251113165331_InitialCreation', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    ALTER TABLE tanatos.tipo_receptor_notificacion DROP COLUMN vigente;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    COMMENT ON TABLE tanatos.tipo_receptor_notificacion IS 'Tabla que contiene los tipos de receptores de notificación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    COMMENT ON COLUMN tanatos.tipo_receptor_notificacion.nombre IS 'Nombre del tipo de receptor de notificación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    COMMENT ON COLUMN tanatos.tipo_receptor_notificacion.id IS 'Identificador del tipo de receptor de notificación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    ALTER TABLE tanatos.tipo_receptor_notificacion ADD vigencia boolean NOT NULL DEFAULT FALSE;
    COMMENT ON COLUMN tanatos.tipo_receptor_notificacion.vigencia IS 'Vigencia del tipo de receptor de notificación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE TABLE tanatos.categoria_norma (
        id bigint NOT NULL,
        nombre text NOT NULL,
        nombre_corto text,
        descripcion text,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_categoria_norma" PRIMARY KEY (id)
    );
    COMMENT ON TABLE tanatos.categoria_norma IS 'Tabla que contiene las categorías de las normas';
    COMMENT ON COLUMN tanatos.categoria_norma.id IS 'Identificador de la categoría.';
    COMMENT ON COLUMN tanatos.categoria_norma.nombre IS 'Nombre de la categoría.';
    COMMENT ON COLUMN tanatos.categoria_norma.nombre_corto IS 'Nombre corto de la categoría.';
    COMMENT ON COLUMN tanatos.categoria_norma.descripcion IS 'Descripción de la categoría.';
    COMMENT ON COLUMN tanatos.categoria_norma.vigencia IS 'Vigencia de la categoría.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE TABLE tanatos.destinatario_notificacion (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        sub text NOT NULL,
        id_tipo_receptor bigint NOT NULL,
        destino text NOT NULL,
        codigo_validacion text NOT NULL,
        intentos_validacion smallint NOT NULL,
        validado boolean NOT NULL,
        fecha_creacion timestamp with time zone NOT NULL,
        fecha_eliminacion timestamp with time zone NOT NULL,
        vigente boolean NOT NULL,
        CONSTRAINT "PK_destinatario_notificacion" PRIMARY KEY (id),
        CONSTRAINT "FK_destinatario_notificacion_tipo_receptor_notificacion_id_tip~" FOREIGN KEY (id_tipo_receptor) REFERENCES tanatos.tipo_receptor_notificacion (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.destinatario_notificacion IS 'Tabla que contiene los destinatarios de las notificaciones de un usuario.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.id IS 'Identificador del destinatario de notificación.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.sub IS 'Usuario al que pertenece el destinatario de notificación.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.id_tipo_receptor IS 'Identificador del tipo de receptor asociado al destinatario.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.destino IS 'Destino de la notificación. Puede ser un correo o un número de Whatsapp.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.codigo_validacion IS 'Código generado para validar que el destinatario se suscribe a la notificación.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.intentos_validacion IS 'Cantidad de intentos de validar al destinatario.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.validado IS 'Identifica si el destinatario ya fue validado.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.fecha_creacion IS 'Fecha en que se creó el destinatario.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.fecha_eliminacion IS 'Fecha en que se eliminó el destinatario.';
    COMMENT ON COLUMN tanatos.destinatario_notificacion.vigente IS 'Vigencia del destinatario.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE TABLE tanatos.tipo_fiscalizador (
        id bigint NOT NULL,
        nombre text NOT NULL,
        nombre_corto text,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_tipo_fiscalizador" PRIMARY KEY (id)
    );
    COMMENT ON TABLE tanatos.tipo_fiscalizador IS 'Tabla que contiene los tipos de fiscalizadores de las normas.';
    COMMENT ON COLUMN tanatos.tipo_fiscalizador.id IS 'Identificador del tipo de fiscalizador.';
    COMMENT ON COLUMN tanatos.tipo_fiscalizador.nombre IS 'Nombre del tipo de fiscalizador.';
    COMMENT ON COLUMN tanatos.tipo_fiscalizador.nombre_corto IS 'Nombre corto del tipo de fiscalizador.';
    COMMENT ON COLUMN tanatos.tipo_fiscalizador.vigencia IS 'Vigencia del tipo de fiscalizador.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE TABLE tanatos.tipo_periodicidad (
        id bigint NOT NULL,
        nombre text NOT NULL,
        descripcion text,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_tipo_periodicidad" PRIMARY KEY (id)
    );
    COMMENT ON TABLE tanatos.tipo_periodicidad IS 'Tabla que contiene los tipos de periodicidad.';
    COMMENT ON COLUMN tanatos.tipo_periodicidad.id IS 'Identificador del tipo de periodicidad.';
    COMMENT ON COLUMN tanatos.tipo_periodicidad.nombre IS 'Nombre del tipo de periodicidad.';
    COMMENT ON COLUMN tanatos.tipo_periodicidad.descripcion IS 'Descripción del tipo de periodicidad.';
    COMMENT ON COLUMN tanatos.tipo_periodicidad.vigencia IS 'Vigencia del tipo de periodicidad.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE TABLE tanatos.tipo_unidad_tiempo (
        id bigint NOT NULL,
        nombre text NOT NULL,
        cant_segundos bigint NOT NULL,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_tipo_unidad_tiempo" PRIMARY KEY (id)
    );
    COMMENT ON TABLE tanatos.tipo_unidad_tiempo IS 'Tabla que contiene los tipos de unidades de tiempo.';
    COMMENT ON COLUMN tanatos.tipo_unidad_tiempo.id IS 'Identificador del tipo de unidad de tiempo.';
    COMMENT ON COLUMN tanatos.tipo_unidad_tiempo.nombre IS 'Nombre del tipo de unidad de tiempo.';
    COMMENT ON COLUMN tanatos.tipo_unidad_tiempo.cant_segundos IS 'Cantidad de segundos que representan a la unidad de tiempo.';
    COMMENT ON COLUMN tanatos.tipo_unidad_tiempo.vigencia IS 'Vigencia del tipo de unidad de tiempo.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE INDEX "IX_destinatario_notificacion_id_tipo_receptor" ON tanatos.destinatario_notificacion (id_tipo_receptor);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    CREATE INDEX "IX_destinatario_notificacion_sub_id_tipo_receptor" ON tanatos.destinatario_notificacion (sub, id_tipo_receptor);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117132506_TablasTipo') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251117132506_TablasTipo', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE TABLE tanatos.template (
        id bigint NOT NULL,
        id_template_padre bigint,
        nombre text NOT NULL,
        descripcion text NOT NULL,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_template" PRIMARY KEY (id),
        CONSTRAINT "FK_template_template_id_template_padre" FOREIGN KEY (id_template_padre) REFERENCES tanatos.template (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.template IS 'Tabla que contiene los templates de normas a inscribirse.';
    COMMENT ON COLUMN tanatos.template.id IS 'Identificador del template.';
    COMMENT ON COLUMN tanatos.template.id_template_padre IS 'Identificador del template padre.';
    COMMENT ON COLUMN tanatos.template.nombre IS 'Nombre del template.';
    COMMENT ON COLUMN tanatos.template.descripcion IS 'Descripcion del template.';
    COMMENT ON COLUMN tanatos.template.vigencia IS 'Vigencia del template.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE TABLE tanatos.inscripcion_template (
        sub text NOT NULL,
        id_template bigint NOT NULL,
        fecha_activacion timestamp with time zone NOT NULL,
        fecha_desactivacion timestamp with time zone,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_inscripcion_template" PRIMARY KEY (sub, id_template),
        CONSTRAINT "FK_inscripcion_template_template_id_template" FOREIGN KEY (id_template) REFERENCES tanatos.template (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.inscripcion_template IS 'Tabla que contiene los templates a los que un usuario está inscrito.';
    COMMENT ON COLUMN tanatos.inscripcion_template.sub IS 'Usuario al que está asociada la inscripción.';
    COMMENT ON COLUMN tanatos.inscripcion_template.id_template IS 'Identificador del template al que está inscrito el usuario.';
    COMMENT ON COLUMN tanatos.inscripcion_template.fecha_activacion IS 'Fecha en que se activa la inscripción.';
    COMMENT ON COLUMN tanatos.inscripcion_template.fecha_desactivacion IS 'Fecha en que se desactiva la inscripción.';
    COMMENT ON COLUMN tanatos.inscripcion_template.vigencia IS 'Vigencia de la inscripción.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE TABLE tanatos.template_norma (
        id bigint NOT NULL,
        id_template bigint NOT NULL,
        nombre text NOT NULL,
        descripcion text,
        id_tipo_periodicidad bigint,
        multa text,
        id_categoria_norma bigint NOT NULL,
        CONSTRAINT "PK_template_norma" PRIMARY KEY (id),
        CONSTRAINT "FK_template_norma_categoria_norma_id_categoria_norma" FOREIGN KEY (id_categoria_norma) REFERENCES tanatos.categoria_norma (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_template_norma_template_id_template" FOREIGN KEY (id_template) REFERENCES tanatos.template (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_template_norma_tipo_periodicidad_id_tipo_periodicidad" FOREIGN KEY (id_tipo_periodicidad) REFERENCES tanatos.tipo_periodicidad (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.template_norma IS 'Tabla que contiene las normas asociadas a un template.';
    COMMENT ON COLUMN tanatos.template_norma.id IS 'Identificador de la norma asociada al template.';
    COMMENT ON COLUMN tanatos.template_norma.id_template IS 'Identificador del template al que pertenece la norma.';
    COMMENT ON COLUMN tanatos.template_norma.nombre IS 'Nombre de la norma.';
    COMMENT ON COLUMN tanatos.template_norma.descripcion IS 'Descripcion de la norma.';
    COMMENT ON COLUMN tanatos.template_norma.id_tipo_periodicidad IS 'Identificador del tipo de periodicidad asociado a la norma.';
    COMMENT ON COLUMN tanatos.template_norma.multa IS 'Multa de no cumplir con la norma';
    COMMENT ON COLUMN tanatos.template_norma.id_categoria_norma IS 'Identificador de la categoría a la que pertenece la norma.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE TABLE tanatos.template_norma_fiscalizador (
        id_template_norma bigint NOT NULL,
        id_tipo_fiscalizador bigint NOT NULL,
        CONSTRAINT "PK_template_norma_fiscalizador" PRIMARY KEY (id_template_norma, id_tipo_fiscalizador),
        CONSTRAINT "FK_template_norma_fiscalizador_template_norma_id_template_norma" FOREIGN KEY (id_template_norma) REFERENCES tanatos.template_norma (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_template_norma_fiscalizador_tipo_fiscalizador_id_tipo_fisca~" FOREIGN KEY (id_tipo_fiscalizador) REFERENCES tanatos.tipo_fiscalizador (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.template_norma_fiscalizador IS 'Tabla que contiene la relación entre un template norma y un fiscalizador.';
    COMMENT ON COLUMN tanatos.template_norma_fiscalizador.id_template_norma IS 'Identificador de la norma perteneciente a un template.';
    COMMENT ON COLUMN tanatos.template_norma_fiscalizador.id_tipo_fiscalizador IS 'Identificador del tipo de fiscalizador.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE TABLE tanatos.template_norma_notificacion (
        id_template_norma bigint NOT NULL,
        id_tipo_unidad_tiempo_antelacion bigint NOT NULL,
        cant_antelacion integer NOT NULL,
        CONSTRAINT "PK_template_norma_notificacion" PRIMARY KEY (id_template_norma, id_tipo_unidad_tiempo_antelacion),
        CONSTRAINT "FK_template_norma_notificacion_template_norma_id_template_norma" FOREIGN KEY (id_template_norma) REFERENCES tanatos.template_norma (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_template_norma_notificacion_tipo_unidad_tiempo_id_tipo_unid~" FOREIGN KEY (id_tipo_unidad_tiempo_antelacion) REFERENCES tanatos.tipo_unidad_tiempo (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.template_norma_notificacion IS 'Tabla que contiene las notificaciones asociadas a una template norma.';
    COMMENT ON COLUMN tanatos.template_norma_notificacion.id_template_norma IS 'Identificador de la template norma.';
    COMMENT ON COLUMN tanatos.template_norma_notificacion.id_tipo_unidad_tiempo_antelacion IS 'Identificador del tipo de unidad de tiempo a usar para la notificación.';
    COMMENT ON COLUMN tanatos.template_norma_notificacion.cant_antelacion IS 'Cantidad de unidades de tiempo a usar para la notificación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_inscripcion_template_id_template" ON tanatos.inscripcion_template (id_template);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_template_id_template_padre" ON tanatos.template (id_template_padre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_template_norma_id_categoria_norma" ON tanatos.template_norma (id_categoria_norma);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_template_norma_id_template" ON tanatos.template_norma (id_template);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_template_norma_id_tipo_periodicidad" ON tanatos.template_norma (id_tipo_periodicidad);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_template_norma_fiscalizador_id_tipo_fiscalizador" ON tanatos.template_norma_fiscalizador (id_tipo_fiscalizador);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    CREATE INDEX "IX_template_norma_notificacion_id_tipo_unidad_tiempo_antelacion" ON tanatos.template_norma_notificacion (id_tipo_unidad_tiempo_antelacion);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251117144252_TablasTemplates') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251117144252_TablasTemplates', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205214630_CorreccionVigencia') THEN
    ALTER TABLE tanatos.destinatario_notificacion RENAME COLUMN vigente TO vigencia;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205214630_CorreccionVigencia') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251205214630_CorreccionVigencia', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_fiscalizador DROP CONSTRAINT "FK_template_norma_fiscalizador_template_norma_id_template_norma";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_notificacion DROP CONSTRAINT "FK_template_norma_notificacion_template_norma_id_template_norma";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_notificacion DROP CONSTRAINT "PK_template_norma_notificacion";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_fiscalizador DROP CONSTRAINT "PK_template_norma_fiscalizador";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma DROP CONSTRAINT "PK_template_norma";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    DROP INDEX tanatos."IX_template_norma_id_template";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_notificacion DROP COLUMN id_template_norma;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_fiscalizador DROP COLUMN id_template_norma;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma RENAME COLUMN id TO id_norma;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_notificacion ADD id_template bigint NOT NULL DEFAULT 0;
    COMMENT ON COLUMN tanatos.template_norma_notificacion.id_template IS 'Identificador del template al que pertenece la norma.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_notificacion ADD id_norma bigint NOT NULL DEFAULT 0;
    COMMENT ON COLUMN tanatos.template_norma_notificacion.id_norma IS 'Identificador de la norma asociada al template.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_fiscalizador ADD id_template bigint NOT NULL DEFAULT 0;
    COMMENT ON COLUMN tanatos.template_norma_fiscalizador.id_template IS 'Identificador del template al que pertenece la norma.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_fiscalizador ADD id_norma bigint NOT NULL DEFAULT 0;
    COMMENT ON COLUMN tanatos.template_norma_fiscalizador.id_norma IS 'Identificador de la norma asociada al template.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_notificacion ADD CONSTRAINT "PK_template_norma_notificacion" PRIMARY KEY (id_template, id_norma, id_tipo_unidad_tiempo_antelacion, cant_antelacion);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_fiscalizador ADD CONSTRAINT "PK_template_norma_fiscalizador" PRIMARY KEY (id_template, id_norma, id_tipo_fiscalizador);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma ADD CONSTRAINT "PK_template_norma" PRIMARY KEY (id_template, id_norma);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_fiscalizador ADD CONSTRAINT "FK_template_norma_fiscalizador_template_norma_id_template_id_n~" FOREIGN KEY (id_template, id_norma) REFERENCES tanatos.template_norma (id_template, id_norma) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    ALTER TABLE tanatos.template_norma_notificacion ADD CONSTRAINT "FK_template_norma_notificacion_template_norma_id_template_id_n~" FOREIGN KEY (id_template, id_norma) REFERENCES tanatos.template_norma (id_template, id_norma) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251206192642_CambioPKTemplateNorma') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251206192642_CambioPKTemplateNorma', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209230256_DestCodValidUnique') THEN
    ALTER TABLE tanatos.destinatario_notificacion DROP COLUMN intentos_validacion;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209230256_DestCodValidUnique') THEN
    CREATE UNIQUE INDEX "IX_destinatario_notificacion_codigo_validacion" ON tanatos.destinatario_notificacion (codigo_validacion);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209230256_DestCodValidUnique') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251209230256_DestCodValidUnique', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209235931_QuitaRequireFechaEliminacion') THEN
    ALTER TABLE tanatos.destinatario_notificacion ALTER COLUMN fecha_eliminacion DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209235931_QuitaRequireFechaEliminacion') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251209235931_QuitaRequireFechaEliminacion', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210002949_RegexValidacionTipoReceptor') THEN
    ALTER TABLE tanatos.tipo_receptor_notificacion ADD regex_validacion text;
    COMMENT ON COLUMN tanatos.tipo_receptor_notificacion.regex_validacion IS 'Regex para validar el tipo de receptor.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251210002949_RegexValidacionTipoReceptor') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251210002949_RegexValidacionTipoReceptor', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251212025425_CaducidadFechaValidacionDestinatario') THEN
    ALTER TABLE tanatos.destinatario_notificacion ADD fecha_caducidad_codigo_validacion timestamp with time zone NOT NULL DEFAULT (NOW() + INTERVAL '24 hours');
    COMMENT ON COLUMN tanatos.destinatario_notificacion.fecha_caducidad_codigo_validacion IS 'Fecha en que caduca el código de validación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251212025425_CaducidadFechaValidacionDestinatario') THEN
    ALTER TABLE tanatos.destinatario_notificacion ADD fecha_validacion timestamp with time zone;
    COMMENT ON COLUMN tanatos.destinatario_notificacion.fecha_validacion IS 'Fecha en que se validó el destinatario.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251212025425_CaducidadFechaValidacionDestinatario') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251212025425_CaducidadFechaValidacionDestinatario', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214144425_TablaNegocio') THEN
    CREATE TABLE tanatos.negocio (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        sub text NOT NULL,
        nombre text NOT NULL,
        direccion text,
        fecha_creacion timestamp with time zone NOT NULL,
        fecha_eliminacion timestamp with time zone,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_negocio" PRIMARY KEY (id)
    );
    COMMENT ON TABLE tanatos.negocio IS 'Tabla que contiene los negocios de un usuario.';
    COMMENT ON COLUMN tanatos.negocio.id IS 'Identificador del negocio.';
    COMMENT ON COLUMN tanatos.negocio.sub IS 'Usuario al que pertenece el negocio.';
    COMMENT ON COLUMN tanatos.negocio.nombre IS 'Nombre del negocio.';
    COMMENT ON COLUMN tanatos.negocio.direccion IS 'Dirección del negocio.';
    COMMENT ON COLUMN tanatos.negocio.fecha_creacion IS 'Fecha en que se creó el negocio.';
    COMMENT ON COLUMN tanatos.negocio.fecha_eliminacion IS 'Fecha en que se eliminó el negocio.';
    COMMENT ON COLUMN tanatos.negocio.vigencia IS 'Vigencia del negocio.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214144425_TablaNegocio') THEN
    CREATE INDEX "IX_negocio_sub" ON tanatos.negocio (sub);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214144425_TablaNegocio') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251214144425_TablaNegocio', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214150946_UniqueNegocio') THEN
    DROP INDEX tanatos."IX_negocio_sub";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214150946_UniqueNegocio') THEN
    CREATE UNIQUE INDEX "IX_negocio_sub_nombre" ON tanatos.negocio (sub, nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214150946_UniqueNegocio') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251214150946_UniqueNegocio', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214212505_RelacionNegocioDestinatario') THEN
    DROP INDEX tanatos."IX_destinatario_notificacion_sub_id_tipo_receptor";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214212505_RelacionNegocioDestinatario') THEN
    ALTER TABLE tanatos.destinatario_notificacion ADD id_negocio bigint NOT NULL DEFAULT 0;
    COMMENT ON COLUMN tanatos.destinatario_notificacion.id_negocio IS 'Identificador del negocio del usuario.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214212505_RelacionNegocioDestinatario') THEN
    CREATE INDEX "IX_destinatario_notificacion_id_negocio" ON tanatos.destinatario_notificacion (id_negocio);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214212505_RelacionNegocioDestinatario') THEN
    CREATE INDEX "IX_destinatario_notificacion_sub_id_negocio_id_tipo_receptor" ON tanatos.destinatario_notificacion (sub, id_negocio, id_tipo_receptor);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214212505_RelacionNegocioDestinatario') THEN
    ALTER TABLE tanatos.destinatario_notificacion ADD CONSTRAINT "FK_destinatario_notificacion_negocio_id_negocio" FOREIGN KEY (id_negocio) REFERENCES tanatos.negocio (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214212505_RelacionNegocioDestinatario') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251214212505_RelacionNegocioDestinatario', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215173340_TablaNormaSuscrita') THEN
    CREATE TABLE tanatos.norma_suscrita (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        sub text NOT NULL,
        id_negocio bigint NOT NULL,
        id_template bigint,
        id_norma bigint,
        nombre text,
        descripcion text,
        id_tipo_periodicidad bigint,
        multa text,
        id_categoria_norma bigint,
        orden_visual bigint,
        editable boolean NOT NULL,
        fecha_activacion timestamp with time zone,
        fecha_desactivacion timestamp with time zone,
        activado boolean NOT NULL,
        fecha_creacion timestamp with time zone,
        fecha_eliminacion timestamp with time zone,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_norma_suscrita" PRIMARY KEY (id),
        CONSTRAINT "FK_norma_suscrita_categoria_norma_id_categoria_norma" FOREIGN KEY (id_categoria_norma) REFERENCES tanatos.categoria_norma (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_norma_suscrita_negocio_id_negocio" FOREIGN KEY (id_negocio) REFERENCES tanatos.negocio (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_norma_suscrita_template_norma_id_template_id_norma" FOREIGN KEY (id_template, id_norma) REFERENCES tanatos.template_norma (id_template, id_norma) ON DELETE RESTRICT,
        CONSTRAINT "FK_norma_suscrita_tipo_periodicidad_id_tipo_periodicidad" FOREIGN KEY (id_tipo_periodicidad) REFERENCES tanatos.tipo_periodicidad (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.norma_suscrita IS 'Tabla que contiene las normas a las que está suscrita un negocio del usuario.';
    COMMENT ON COLUMN tanatos.norma_suscrita.id IS 'Identificador de la norma suscrita.';
    COMMENT ON COLUMN tanatos.norma_suscrita.sub IS 'Usuario al que pertenece la norma suscrita.';
    COMMENT ON COLUMN tanatos.norma_suscrita.id_negocio IS 'Identificador del negocio del usuario.';
    COMMENT ON COLUMN tanatos.norma_suscrita.id_template IS 'Identificador del template al que pertenece la norma suscrita.';
    COMMENT ON COLUMN tanatos.norma_suscrita.id_norma IS 'Identificador del template norma al que pertenece la norma suscrita.';
    COMMENT ON COLUMN tanatos.norma_suscrita.nombre IS 'Nombre de la norma.';
    COMMENT ON COLUMN tanatos.norma_suscrita.descripcion IS 'Descripcion de la norma.';
    COMMENT ON COLUMN tanatos.norma_suscrita.id_tipo_periodicidad IS 'Identificador del tipo de periodicidad asociado a la norma.';
    COMMENT ON COLUMN tanatos.norma_suscrita.multa IS 'Multa de no cumplir con la norma.';
    COMMENT ON COLUMN tanatos.norma_suscrita.id_categoria_norma IS 'Identificador de la categoría a la que pertenece la norma.';
    COMMENT ON COLUMN tanatos.norma_suscrita.orden_visual IS 'Orden en que se deben presentar las normas.';
    COMMENT ON COLUMN tanatos.norma_suscrita.editable IS 'Indicador de si es editable la norma.';
    COMMENT ON COLUMN tanatos.norma_suscrita.fecha_activacion IS 'Fecha en que se activó el cumplimiento de la norma.';
    COMMENT ON COLUMN tanatos.norma_suscrita.fecha_desactivacion IS 'Fecha en que se desactivó el cumplimiento de la norma.';
    COMMENT ON COLUMN tanatos.norma_suscrita.activado IS 'Estado de activación de la norma.';
    COMMENT ON COLUMN tanatos.norma_suscrita.fecha_creacion IS 'Fecha en que se creó la norma.';
    COMMENT ON COLUMN tanatos.norma_suscrita.fecha_eliminacion IS 'Fecha en que se eliminó la norma.';
    COMMENT ON COLUMN tanatos.norma_suscrita.vigencia IS 'Vigencia de la norma.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215173340_TablaNormaSuscrita') THEN
    CREATE INDEX "IX_norma_suscrita_id_categoria_norma" ON tanatos.norma_suscrita (id_categoria_norma);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215173340_TablaNormaSuscrita') THEN
    CREATE INDEX "IX_norma_suscrita_id_negocio" ON tanatos.norma_suscrita (id_negocio);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215173340_TablaNormaSuscrita') THEN
    CREATE INDEX "IX_norma_suscrita_id_template_id_norma" ON tanatos.norma_suscrita (id_template, id_norma);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215173340_TablaNormaSuscrita') THEN
    CREATE INDEX "IX_norma_suscrita_id_tipo_periodicidad" ON tanatos.norma_suscrita (id_tipo_periodicidad);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215173340_TablaNormaSuscrita') THEN
    CREATE INDEX "IX_norma_suscrita_sub_id_negocio" ON tanatos.norma_suscrita (sub, id_negocio);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215173340_TablaNormaSuscrita') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251215173340_TablaNormaSuscrita', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217180256_TablaFiscalizadorNormaSuscrita') THEN
    CREATE TABLE tanatos.fiscalizador_norma_suscrita (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        id_norma_suscrita bigint NOT NULL,
        id_tipo_fiscalizador bigint NOT NULL,
        fecha_creacion timestamp with time zone,
        fecha_eliminacion timestamp with time zone,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_fiscalizador_norma_suscrita" PRIMARY KEY (id),
        CONSTRAINT "FK_fiscalizador_norma_suscrita_norma_suscrita_id_norma_suscrita" FOREIGN KEY (id_norma_suscrita) REFERENCES tanatos.norma_suscrita (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_fiscalizador_norma_suscrita_tipo_fiscalizador_id_tipo_fisca~" FOREIGN KEY (id_tipo_fiscalizador) REFERENCES tanatos.tipo_fiscalizador (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.fiscalizador_norma_suscrita IS 'Tabla que contiene los fiscalizadores asociados a una norma suscrita.';
    COMMENT ON COLUMN tanatos.fiscalizador_norma_suscrita.id IS 'Identificador del fiscalizador asociado a una norma suscrita.';
    COMMENT ON COLUMN tanatos.fiscalizador_norma_suscrita.id_norma_suscrita IS 'Identificador de la norma suscrita.';
    COMMENT ON COLUMN tanatos.fiscalizador_norma_suscrita.id_tipo_fiscalizador IS 'Identificador del fiscalizador asociado.';
    COMMENT ON COLUMN tanatos.fiscalizador_norma_suscrita.fecha_creacion IS 'Fecha en que se creó al fiscalizador asociado.';
    COMMENT ON COLUMN tanatos.fiscalizador_norma_suscrita.fecha_eliminacion IS 'Fecha en que se eliminó al fiscalizador asociado.';
    COMMENT ON COLUMN tanatos.fiscalizador_norma_suscrita.vigencia IS 'Vigencia del fiscalizador asociado.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217180256_TablaFiscalizadorNormaSuscrita') THEN
    CREATE INDEX "IX_fiscalizador_norma_suscrita_id_norma_suscrita_vigencia" ON tanatos.fiscalizador_norma_suscrita (id_norma_suscrita, vigencia);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217180256_TablaFiscalizadorNormaSuscrita') THEN
    CREATE INDEX "IX_fiscalizador_norma_suscrita_id_tipo_fiscalizador" ON tanatos.fiscalizador_norma_suscrita (id_tipo_fiscalizador);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251217180256_TablaFiscalizadorNormaSuscrita') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251217180256_TablaFiscalizadorNormaSuscrita', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218171902_TablaNotificacionesNormaSuscrita') THEN
    CREATE TABLE tanatos.notificacion_norma_suscrita (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        id_norma_suscrita bigint NOT NULL,
        id_tipo_unidad_tiempo_antelacion bigint NOT NULL,
        cant_antelacion integer NOT NULL,
        fecha_creacion timestamp with time zone,
        fecha_eliminacion timestamp with time zone,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_notificacion_norma_suscrita" PRIMARY KEY (id),
        CONSTRAINT "FK_notificacion_norma_suscrita_norma_suscrita_id_norma_suscrita" FOREIGN KEY (id_norma_suscrita) REFERENCES tanatos.norma_suscrita (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_notificacion_norma_suscrita_tipo_unidad_tiempo_id_tipo_unid~" FOREIGN KEY (id_tipo_unidad_tiempo_antelacion) REFERENCES tanatos.tipo_unidad_tiempo (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.notificacion_norma_suscrita IS 'Tabla que contiene las notificaciones asociados a una norma suscrita.';
    COMMENT ON COLUMN tanatos.notificacion_norma_suscrita.id IS 'Identificador de la notificación asociada a una norma suscrita.';
    COMMENT ON COLUMN tanatos.notificacion_norma_suscrita.id_norma_suscrita IS 'Identificador de la norma suscrita.';
    COMMENT ON COLUMN tanatos.notificacion_norma_suscrita.id_tipo_unidad_tiempo_antelacion IS 'Identificador del tipo de unidad de tiempo a usar para la notificación.';
    COMMENT ON COLUMN tanatos.notificacion_norma_suscrita.cant_antelacion IS 'Cantidad de unidades de tiempo a usar para la notificación.';
    COMMENT ON COLUMN tanatos.notificacion_norma_suscrita.fecha_creacion IS 'Fecha en que se creó la notificación asociada.';
    COMMENT ON COLUMN tanatos.notificacion_norma_suscrita.fecha_eliminacion IS 'Fecha en que se eliminó la notificación asociada.';
    COMMENT ON COLUMN tanatos.notificacion_norma_suscrita.vigencia IS 'Vigencia de la notificación asociada.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218171902_TablaNotificacionesNormaSuscrita') THEN
    CREATE INDEX "IX_notificacion_norma_suscrita_id_norma_suscrita_vigencia" ON tanatos.notificacion_norma_suscrita (id_norma_suscrita, vigencia);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218171902_TablaNotificacionesNormaSuscrita') THEN
    CREATE INDEX "IX_notificacion_norma_suscrita_id_tipo_unidad_tiempo_antelacion" ON tanatos.notificacion_norma_suscrita (id_tipo_unidad_tiempo_antelacion);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218171902_TablaNotificacionesNormaSuscrita') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251218171902_TablaNotificacionesNormaSuscrita', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218212856_RemoveUniqueNegocio') THEN
    DROP INDEX tanatos."IX_negocio_sub_nombre";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218212856_RemoveUniqueNegocio') THEN
    CREATE INDEX "IX_negocio_sub_nombre" ON tanatos.negocio (sub, nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218212856_RemoveUniqueNegocio') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251218212856_RemoveUniqueNegocio', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251220132132_TablaHistorialNormaSuscrita') THEN
    CREATE TABLE tanatos.historial_norma_suscrita (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        id_norma_suscrita bigint NOT NULL,
        fecha_vencimiento timestamp with time zone NOT NULL,
        fecha_completitud timestamp with time zone,
        fecha_creacion timestamp with time zone NOT NULL,
        fecha_eliminacion timestamp with time zone,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_historial_norma_suscrita" PRIMARY KEY (id),
        CONSTRAINT "FK_historial_norma_suscrita_norma_suscrita_id_norma_suscrita" FOREIGN KEY (id_norma_suscrita) REFERENCES tanatos.norma_suscrita (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.historial_norma_suscrita IS 'Tabla que contiene el historial de ejecución de una norma suscrita.';
    COMMENT ON COLUMN tanatos.historial_norma_suscrita.id IS 'Identificador del historial de ejecución de una norma suscrita.';
    COMMENT ON COLUMN tanatos.historial_norma_suscrita.id_norma_suscrita IS 'Identificador de la norma suscrita.';
    COMMENT ON COLUMN tanatos.historial_norma_suscrita.fecha_vencimiento IS 'Fecha en que vencerá la ejecución de la norma suscrita';
    COMMENT ON COLUMN tanatos.historial_norma_suscrita.fecha_completitud IS 'Fecha en que se completó la ejecución de la norma suscrita.';
    COMMENT ON COLUMN tanatos.historial_norma_suscrita.fecha_creacion IS 'Fecha en que se creó el registro.';
    COMMENT ON COLUMN tanatos.historial_norma_suscrita.fecha_eliminacion IS 'Fecha en que se eliminó el registro.';
    COMMENT ON COLUMN tanatos.historial_norma_suscrita.vigencia IS 'Vigencia del registro.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251220132132_TablaHistorialNormaSuscrita') THEN
    CREATE INDEX "IX_historial_norma_suscrita_fecha_vencimiento" ON tanatos.historial_norma_suscrita (fecha_vencimiento);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251220132132_TablaHistorialNormaSuscrita') THEN
    CREATE INDEX "IX_historial_norma_suscrita_id_norma_suscrita_fecha_vencimiento" ON tanatos.historial_norma_suscrita (id_norma_suscrita, fecha_vencimiento);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251220132132_TablaHistorialNormaSuscrita') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251220132132_TablaHistorialNormaSuscrita', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133226_AgregaIdNegocioInscripcionTemplate') THEN
    ALTER TABLE tanatos.inscripcion_template DROP CONSTRAINT "PK_inscripcion_template";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133226_AgregaIdNegocioInscripcionTemplate') THEN
    ALTER TABLE tanatos.inscripcion_template ADD id_negocio bigint NOT NULL DEFAULT 0;
    COMMENT ON COLUMN tanatos.inscripcion_template.id_negocio IS 'Identificador del negocio del usuario.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133226_AgregaIdNegocioInscripcionTemplate') THEN
    ALTER TABLE tanatos.inscripcion_template ADD CONSTRAINT "PK_inscripcion_template" PRIMARY KEY (sub, id_negocio, id_template);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133226_AgregaIdNegocioInscripcionTemplate') THEN
    CREATE INDEX "IX_inscripcion_template_id_negocio" ON tanatos.inscripcion_template (id_negocio);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133226_AgregaIdNegocioInscripcionTemplate') THEN
    ALTER TABLE tanatos.inscripcion_template ADD CONSTRAINT "FK_inscripcion_template_negocio_id_negocio" FOREIGN KEY (id_negocio) REFERENCES tanatos.negocio (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251222133226_AgregaIdNegocioInscripcionTemplate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251222133226_AgregaIdNegocioInscripcionTemplate', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112193435_TablasRubroActividad') THEN
    ALTER TABLE tanatos.negocio ADD id_tipo_actividad bigint;
    COMMENT ON COLUMN tanatos.negocio.id_tipo_actividad IS 'Identificador de la actividad que efectúa el negocio.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112193435_TablasRubroActividad') THEN
    CREATE TABLE tanatos.tipo_rubro (
        id bigint NOT NULL,
        nombre text NOT NULL,
        descripcion text,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_tipo_rubro" PRIMARY KEY (id)
    );
    COMMENT ON TABLE tanatos.tipo_rubro IS 'Tabla que contiene los rubros a los que puede pertenecer un negocio.';
    COMMENT ON COLUMN tanatos.tipo_rubro.id IS 'Identificador del rubro.';
    COMMENT ON COLUMN tanatos.tipo_rubro.nombre IS 'Nombre del rubro.';
    COMMENT ON COLUMN tanatos.tipo_rubro.descripcion IS 'Descripción del rubro.';
    COMMENT ON COLUMN tanatos.tipo_rubro.vigencia IS 'Vigencia del rubro.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112193435_TablasRubroActividad') THEN
    CREATE TABLE tanatos.tipo_actividad (
        id bigint NOT NULL,
        id_tipo_rubro bigint NOT NULL,
        nombre text NOT NULL,
        descripcion text,
        vigencia boolean NOT NULL,
        CONSTRAINT "PK_tipo_actividad" PRIMARY KEY (id),
        CONSTRAINT "FK_tipo_actividad_tipo_rubro_id_tipo_rubro" FOREIGN KEY (id_tipo_rubro) REFERENCES tanatos.tipo_rubro (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.tipo_actividad IS 'Tabla que contiene las actividades que puede hacer un negocio.';
    COMMENT ON COLUMN tanatos.tipo_actividad.id IS 'Identificador de la actividad.';
    COMMENT ON COLUMN tanatos.tipo_actividad.id_tipo_rubro IS 'Identificador del rubro al que pertenece la actividad.';
    COMMENT ON COLUMN tanatos.tipo_actividad.nombre IS 'Nombre de la actividad.';
    COMMENT ON COLUMN tanatos.tipo_actividad.descripcion IS 'Descripción de la actividad.';
    COMMENT ON COLUMN tanatos.tipo_actividad.vigencia IS 'Vigencia de la actividad.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112193435_TablasRubroActividad') THEN
    CREATE INDEX "IX_negocio_id_tipo_actividad" ON tanatos.negocio (id_tipo_actividad);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112193435_TablasRubroActividad') THEN
    CREATE INDEX "IX_tipo_actividad_id_tipo_rubro" ON tanatos.tipo_actividad (id_tipo_rubro);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112193435_TablasRubroActividad') THEN
    ALTER TABLE tanatos.negocio ADD CONSTRAINT "FK_negocio_tipo_actividad_id_tipo_actividad" FOREIGN KEY (id_tipo_actividad) REFERENCES tanatos.tipo_actividad (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260112193435_TablasRubroActividad') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260112193435_TablasRubroActividad', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113192226_TablasTemplateActividad') THEN
    CREATE TABLE tanatos.template_actividad (
        id_template bigint NOT NULL,
        id_tipo_actividad bigint NOT NULL,
        CONSTRAINT "PK_template_actividad" PRIMARY KEY (id_template, id_tipo_actividad),
        CONSTRAINT "FK_template_actividad_template_id_template" FOREIGN KEY (id_template) REFERENCES tanatos.template (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_template_actividad_tipo_actividad_id_tipo_actividad" FOREIGN KEY (id_tipo_actividad) REFERENCES tanatos.tipo_actividad (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.template_actividad IS 'Tabla que contiene la recomendación de templates según tipo de actividad de un negocio.';
    COMMENT ON COLUMN tanatos.template_actividad.id_template IS 'Identificador del template.';
    COMMENT ON COLUMN tanatos.template_actividad.id_tipo_actividad IS 'Identificador del tipo de actividad del negocio.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113192226_TablasTemplateActividad') THEN
    CREATE INDEX "IX_template_actividad_id_tipo_actividad" ON tanatos.template_actividad (id_tipo_actividad);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260113192226_TablasTemplateActividad') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260113192226_TablasTemplateActividad', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119172016_CronTipoPeriodicidad') THEN
    ALTER TABLE tanatos.tipo_periodicidad ADD cron text;
    COMMENT ON COLUMN tanatos.tipo_periodicidad.cron IS 'Cron del tipo de periodicidad.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119172016_CronTipoPeriodicidad') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260119172016_CronTipoPeriodicidad', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119232011_TablaHistorialNotificacion') THEN
    CREATE TABLE tanatos.historial_notificacion (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        id_historial_norma_suscrita bigint NOT NULL,
        id_destinatario_notificacion bigint NOT NULL,
        fecha_programacion timestamp with time zone NOT NULL,
        fecha_ejecucion timestamp with time zone,
        CONSTRAINT "PK_historial_notificacion" PRIMARY KEY (id),
        CONSTRAINT "FK_historial_notificacion_destinatario_notificacion_id_destina~" FOREIGN KEY (id_destinatario_notificacion) REFERENCES tanatos.destinatario_notificacion (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_historial_notificacion_historial_norma_suscrita_id_historia~" FOREIGN KEY (id_historial_norma_suscrita) REFERENCES tanatos.historial_norma_suscrita (id) ON DELETE RESTRICT
    );
    COMMENT ON TABLE tanatos.historial_notificacion IS 'Tabla que contiene el historial de notificaciones de una norma suscrita.';
    COMMENT ON COLUMN tanatos.historial_notificacion.id IS 'Identificador del historial de notificación de una norma suscrita.';
    COMMENT ON COLUMN tanatos.historial_notificacion.id_historial_norma_suscrita IS 'Identificador del historial de ejecución de una norma suscrita.';
    COMMENT ON COLUMN tanatos.historial_notificacion.id_destinatario_notificacion IS 'Identificador del destinatario de la notificación.';
    COMMENT ON COLUMN tanatos.historial_notificacion.fecha_programacion IS 'Fecha en que se programó el envío de la notificación.';
    COMMENT ON COLUMN tanatos.historial_notificacion.fecha_ejecucion IS 'Fecha en que se ejecutó el envío de la notificación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119232011_TablaHistorialNotificacion') THEN
    CREATE INDEX "IX_historial_notificacion_id_destinatario_notificacion" ON tanatos.historial_notificacion (id_destinatario_notificacion);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119232011_TablaHistorialNotificacion') THEN
    CREATE INDEX "IX_historial_notificacion_id_historial_norma_suscrita" ON tanatos.historial_notificacion (id_historial_norma_suscrita);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260119232011_TablaHistorialNotificacion') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260119232011_TablaHistorialNotificacion', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260120231545_ColumnsHistorialNotificacion') THEN
    ALTER TABLE tanatos.historial_notificacion ADD cant_antelacion integer;
    COMMENT ON COLUMN tanatos.historial_notificacion.cant_antelacion IS 'Cantidad de unidades de tiempo correspondientes a la notificación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260120231545_ColumnsHistorialNotificacion') THEN
    ALTER TABLE tanatos.historial_notificacion ADD id_tipo_unidad_tiempo_antelacion bigint;
    COMMENT ON COLUMN tanatos.historial_notificacion.id_tipo_unidad_tiempo_antelacion IS 'Identificador del tipo de unidad de tiempo correspondiente a la notificación.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260120231545_ColumnsHistorialNotificacion') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260120231545_ColumnsHistorialNotificacion', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121144405_ColumnsMetadataHistorialNotificacion') THEN
    ALTER TABLE tanatos.historial_notificacion ADD fecha_creacion timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    COMMENT ON COLUMN tanatos.historial_notificacion.fecha_creacion IS 'Fecha en que se creó el registro.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121144405_ColumnsMetadataHistorialNotificacion') THEN
    ALTER TABLE tanatos.historial_notificacion ADD fecha_eliminacion timestamp with time zone;
    COMMENT ON COLUMN tanatos.historial_notificacion.fecha_eliminacion IS 'Fecha en que se eliminó el registro.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121144405_ColumnsMetadataHistorialNotificacion') THEN
    ALTER TABLE tanatos.historial_notificacion ADD vigencia boolean NOT NULL DEFAULT FALSE;
    COMMENT ON COLUMN tanatos.historial_notificacion.vigencia IS 'Vigencia del registro.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121144405_ColumnsMetadataHistorialNotificacion') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260121144405_ColumnsMetadataHistorialNotificacion', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121213826_ColumnProcesoNotificacionNormaSuscrita') THEN
    ALTER TABLE tanatos.norma_suscrita ADD procesos_notificaciones jsonb;
    COMMENT ON COLUMN tanatos.norma_suscrita.procesos_notificaciones IS 'Procesos de notificaciones asociados a la norma suscrita.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260121213826_ColumnProcesoNotificacionNormaSuscrita') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260121213826_ColumnProcesoNotificacionNormaSuscrita', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260125163311_NombrePluralUnidadTiempo') THEN
    ALTER TABLE tanatos.tipo_unidad_tiempo ADD nombre_plural text;
    COMMENT ON COLUMN tanatos.tipo_unidad_tiempo.nombre_plural IS 'Nombre plural del tipo de unidad de tiempo.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260125163311_NombrePluralUnidadTiempo') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260125163311_NombrePluralUnidadTiempo', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260125164127_DeltasPeriodicidad') THEN
    ALTER TABLE tanatos.tipo_periodicidad ADD delta_annos integer;
    COMMENT ON COLUMN tanatos.tipo_periodicidad.delta_annos IS 'Delta en años de la periodicidad.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260125164127_DeltasPeriodicidad') THEN
    ALTER TABLE tanatos.tipo_periodicidad ADD delta_dias integer;
    COMMENT ON COLUMN tanatos.tipo_periodicidad.delta_dias IS 'Delta en días de la periodicidad.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260125164127_DeltasPeriodicidad') THEN
    ALTER TABLE tanatos.tipo_periodicidad ADD delta_meses integer;
    COMMENT ON COLUMN tanatos.tipo_periodicidad.delta_meses IS 'Delta en meses de la periodicidad.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260125164127_DeltasPeriodicidad') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260125164127_DeltasPeriodicidad', '9.0.11');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127234100_ColumnHermesIdHistorialNotificacion') THEN
    ALTER TABLE tanatos.historial_notificacion ADD hermes_queue_message_id text;
    COMMENT ON COLUMN tanatos.historial_notificacion.hermes_queue_message_id IS 'ID del mensaje en la cola de envío de correo de Hermes.';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260127234100_ColumnHermesIdHistorialNotificacion') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260127234100_ColumnHermesIdHistorialNotificacion', '9.0.11');
    END IF;
END $EF$;
COMMIT;

