// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TanatosAPI.Entities.Contexts;

#nullable disable

namespace TanatosAPI.Migrations
{
    [DbContext(typeof(TanatosDbContext))]
    [Migration("20251205214630_CorreccionVigencia")]
    partial class CorreccionVigencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TanatosAPI.Entities.Models.CategoriaNorma", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador de la categoría.");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion")
                        .HasComment("Descripción de la categoría.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre de la categoría.");

                    b.Property<string>("NombreCorto")
                        .HasColumnType("text")
                        .HasColumnName("nombre_corto")
                        .HasComment("Nombre corto de la categoría.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia de la categoría.");

                    b.HasKey("Id");

                    b.ToTable("categoria_norma", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene las categorías de las normas");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.DestinatarioNotificacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del destinatario de notificación.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoValidacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_validacion")
                        .HasComment("Código generado para validar que el destinatario se suscribe a la notificación.");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destino")
                        .HasComment("Destino de la notificación. Puede ser un correo o un número de Whatsapp.");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasComment("Fecha en que se creó el destinatario.");

                    b.Property<DateTimeOffset>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion")
                        .HasComment("Fecha en que se eliminó el destinatario.");

                    b.Property<long>("IdTipoReceptor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_receptor")
                        .HasComment("Identificador del tipo de receptor asociado al destinatario.");

                    b.Property<short>("IntentosValidacion")
                        .HasColumnType("smallint")
                        .HasColumnName("intentos_validacion")
                        .HasComment("Cantidad de intentos de validar al destinatario.");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub")
                        .HasComment("Usuario al que pertenece el destinatario de notificación.");

                    b.Property<bool>("Validado")
                        .HasColumnType("boolean")
                        .HasColumnName("validado")
                        .HasComment("Identifica si el destinatario ya fue validado.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del destinatario.");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoReceptor");

                    b.HasIndex("Sub", "IdTipoReceptor");

                    b.ToTable("destinatario_notificacion", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los destinatarios de las notificaciones de un usuario.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.InscripcionTemplate", b =>
                {
                    b.Property<string>("Sub")
                        .HasColumnType("text")
                        .HasColumnName("sub")
                        .HasComment("Usuario al que está asociada la inscripción.");

                    b.Property<long>("IdTemplate")
                        .HasColumnType("bigint")
                        .HasColumnName("id_template")
                        .HasComment("Identificador del template al que está inscrito el usuario.");

                    b.Property<DateTimeOffset>("FechaActivacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_activacion")
                        .HasComment("Fecha en que se activa la inscripción.");

                    b.Property<DateTimeOffset?>("FechaDesactivacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_desactivacion")
                        .HasComment("Fecha en que se desactiva la inscripción.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia de la inscripción.");

                    b.HasKey("Sub", "IdTemplate");

                    b.HasIndex("IdTemplate");

                    b.ToTable("inscripcion_template", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los templates a los que un usuario está inscrito.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.Template", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del template.");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion")
                        .HasComment("Descripcion del template.");

                    b.Property<long?>("IdTemplatePadre")
                        .HasColumnType("bigint")
                        .HasColumnName("id_template_padre")
                        .HasComment("Identificador del template padre.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del template.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del template.");

                    b.HasKey("Id");

                    b.HasIndex("IdTemplatePadre");

                    b.ToTable("template", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los templates de normas a inscribirse.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNorma", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador de la norma asociada al template.");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion")
                        .HasComment("Descripcion de la norma.");

                    b.Property<long>("IdCategoriaNorma")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria_norma")
                        .HasComment("Identificador de la categoría a la que pertenece la norma.");

                    b.Property<long>("IdTemplate")
                        .HasColumnType("bigint")
                        .HasColumnName("id_template")
                        .HasComment("Identificador del template al que pertenece la norma.");

                    b.Property<long?>("IdTipoPeriodicidad")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_periodicidad")
                        .HasComment("Identificador del tipo de periodicidad asociado a la norma.");

                    b.Property<string>("Multa")
                        .HasColumnType("text")
                        .HasColumnName("multa")
                        .HasComment("Multa de no cumplir con la norma");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre de la norma.");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoriaNorma");

                    b.HasIndex("IdTemplate");

                    b.HasIndex("IdTipoPeriodicidad");

                    b.ToTable("template_norma", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene las normas asociadas a un template.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNormaFiscalizador", b =>
                {
                    b.Property<long>("IdTemplateNorma")
                        .HasColumnType("bigint")
                        .HasColumnName("id_template_norma")
                        .HasComment("Identificador de la norma perteneciente a un template.");

                    b.Property<long>("IdTipoFiscalizador")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_fiscalizador")
                        .HasComment("Identificador del tipo de fiscalizador.");

                    b.HasKey("IdTemplateNorma", "IdTipoFiscalizador");

                    b.HasIndex("IdTipoFiscalizador");

                    b.ToTable("template_norma_fiscalizador", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene la relación entre un template norma y un fiscalizador.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNormaNotificacion", b =>
                {
                    b.Property<long>("IdTemplateNorma")
                        .HasColumnType("bigint")
                        .HasColumnName("id_template_norma")
                        .HasComment("Identificador de la template norma.");

                    b.Property<long>("IdTipoUnidadTiempoAntelacion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_unidad_tiempo_antelacion")
                        .HasComment("Identificador del tipo de unidad de tiempo a usar para la notificación.");

                    b.Property<int>("CantAntelacion")
                        .HasColumnType("integer")
                        .HasColumnName("cant_antelacion")
                        .HasComment("Cantidad de unidades de tiempo a usar para la notificación.");

                    b.HasKey("IdTemplateNorma", "IdTipoUnidadTiempoAntelacion");

                    b.HasIndex("IdTipoUnidadTiempoAntelacion");

                    b.ToTable("template_norma_notificacion", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene las notificaciones asociadas a una template norma.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoFiscalizador", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del tipo de fiscalizador.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del tipo de fiscalizador.");

                    b.Property<string>("NombreCorto")
                        .HasColumnType("text")
                        .HasColumnName("nombre_corto")
                        .HasComment("Nombre corto del tipo de fiscalizador.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del tipo de fiscalizador.");

                    b.HasKey("Id");

                    b.ToTable("tipo_fiscalizador", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los tipos de fiscalizadores de las normas.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoPeriodicidad", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del tipo de periodicidad.");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion")
                        .HasComment("Descripción del tipo de periodicidad.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del tipo de periodicidad.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del tipo de periodicidad.");

                    b.HasKey("Id");

                    b.ToTable("tipo_periodicidad", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los tipos de periodicidad.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoReceptorNotificacion", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del tipo de receptor de notificación.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del tipo de receptor de notificación.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del tipo de receptor de notificación.");

                    b.HasKey("Id");

                    b.ToTable("tipo_receptor_notificacion", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los tipos de receptores de notificación.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoUnidadTiempo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del tipo de unidad de tiempo.");

                    b.Property<long>("CantSegundos")
                        .HasColumnType("bigint")
                        .HasColumnName("cant_segundos")
                        .HasComment("Cantidad de segundos que representan a la unidad de tiempo.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del tipo de unidad de tiempo.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del tipo de unidad de tiempo.");

                    b.HasKey("Id");

                    b.ToTable("tipo_unidad_tiempo", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los tipos de unidades de tiempo.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.DestinatarioNotificacion", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.TipoReceptorNotificacion", "TipoReceptorNotificacion")
                        .WithMany("DestinatariosNotificaciones")
                        .HasForeignKey("IdTipoReceptor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoReceptorNotificacion");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.InscripcionTemplate", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.Template", "Template")
                        .WithMany("InscripcionesTemplate")
                        .HasForeignKey("IdTemplate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.Template", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.Template", "TemplatePadre")
                        .WithMany("TemplatesHijos")
                        .HasForeignKey("IdTemplatePadre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TemplatePadre");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNorma", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.CategoriaNorma", "CategoriaNorma")
                        .WithMany("TemplateNormas")
                        .HasForeignKey("IdCategoriaNorma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.Template", "Template")
                        .WithMany("TemplateNormas")
                        .HasForeignKey("IdTemplate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.TipoPeriodicidad", "TipoPeriodicidad")
                        .WithMany("TemplateNormas")
                        .HasForeignKey("IdTipoPeriodicidad")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaNorma");

                    b.Navigation("Template");

                    b.Navigation("TipoPeriodicidad");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNormaFiscalizador", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.TemplateNorma", "TemplateNorma")
                        .WithMany("TemplateNormaFiscalizadores")
                        .HasForeignKey("IdTemplateNorma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.TipoFiscalizador", "TipoFiscalizador")
                        .WithMany("TemplateNormasFiscalizador")
                        .HasForeignKey("IdTipoFiscalizador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TemplateNorma");

                    b.Navigation("TipoFiscalizador");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNormaNotificacion", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.TemplateNorma", "TemplateNorma")
                        .WithMany("TemplateNormaNotificaciones")
                        .HasForeignKey("IdTemplateNorma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.TipoUnidadTiempo", "TipoUnidadTiempoAntelacion")
                        .WithMany("TemplateNormasNotificacion")
                        .HasForeignKey("IdTipoUnidadTiempoAntelacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TemplateNorma");

                    b.Navigation("TipoUnidadTiempoAntelacion");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.CategoriaNorma", b =>
                {
                    b.Navigation("TemplateNormas");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.Template", b =>
                {
                    b.Navigation("InscripcionesTemplate");

                    b.Navigation("TemplateNormas");

                    b.Navigation("TemplatesHijos");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNorma", b =>
                {
                    b.Navigation("TemplateNormaFiscalizadores");

                    b.Navigation("TemplateNormaNotificaciones");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoFiscalizador", b =>
                {
                    b.Navigation("TemplateNormasFiscalizador");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoPeriodicidad", b =>
                {
                    b.Navigation("TemplateNormas");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoReceptorNotificacion", b =>
                {
                    b.Navigation("DestinatariosNotificaciones");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoUnidadTiempo", b =>
                {
                    b.Navigation("TemplateNormasNotificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
