// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TanatosAPI.Entities.Contexts;

#nullable disable

namespace TanatosAPI.Migrations
{
    [DbContext(typeof(TanatosDbContext))]
    [Migration("20251113165331_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoReceptorNotificacion", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasColumnName("vigente");

                    b.HasKey("Id");

                    b.ToTable("tipo_receptor_notificacion", "tanatos");
                });
#pragma warning restore 612, 618
        }
    }
}
