// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TanatosAPI.Entities.Contexts;

#nullable disable

namespace TanatosAPI.Migrations
{
    [DbContext(typeof(TanatosDbContext))]
    [Migration("20251114215806_TablasTipo")]
    partial class TablasTipo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TanatosAPI.Entities.Models.CategoriaNorma", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador de la categoría.");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion")
                        .HasComment("Descripción de la categoría.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre de la categoría.");

                    b.Property<string>("NombreCorto")
                        .HasColumnType("text")
                        .HasColumnName("nombre_corto")
                        .HasComment("Nombre corto de la categoría.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia de la categoría.");

                    b.HasKey("Id");

                    b.ToTable("categoria_norma", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene las categorías de las normas");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.DestinatarioNotificacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del destinatario de notificación.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoValidacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_validacion")
                        .HasComment("Código generado para validar que el destinatario se suscribe a la notificación.");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destino")
                        .HasComment("Destino de la notificación. Puede ser un correo o un número de Whatsapp.");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasComment("Fecha en que se creó el destinatario.");

                    b.Property<DateTimeOffset>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion")
                        .HasComment("Fecha en que se eliminó el destinatario.");

                    b.Property<long>("IdTipoReceptor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_receptor")
                        .HasComment("Identificador del tipo de receptor asociado al destinatario.");

                    b.Property<short>("IntentosValidacion")
                        .HasColumnType("smallint")
                        .HasColumnName("intentos_validacion")
                        .HasComment("Cantidad de intentos de validar al destinatario.");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub")
                        .HasComment("Usuario al que pertenece el destinatario de notificación.");

                    b.Property<bool>("Validado")
                        .HasColumnType("boolean")
                        .HasColumnName("validado")
                        .HasComment("Identifica si el destinatario ya fue validado.");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean")
                        .HasColumnName("vigente")
                        .HasComment("Vigencia del destinatario.");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoReceptor");

                    b.HasIndex("Sub", "IdTipoReceptor");

                    b.ToTable("destinatario_notificacion", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los destinatarios de las notificaciones de un usuario.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoFiscalizador", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del tipo de fiscalizador.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del tipo de fiscalizador.");

                    b.Property<string>("NombreCorto")
                        .HasColumnType("text")
                        .HasColumnName("nombre_corto")
                        .HasComment("Nombre corto del tipo de fiscalizador.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del tipo de fiscalizador.");

                    b.HasKey("Id");

                    b.ToTable("tipo_fiscalizador", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los tipos de fiscalizadores de las normas.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoPeriodicidad", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del tipo de periodicidad.");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion")
                        .HasComment("Descripción del tipo de periodicidad.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del tipo de periodicidad.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del tipo de periodicidad.");

                    b.HasKey("Id");

                    b.ToTable("TiposPeriodicidades");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoReceptorNotificacion", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del tipo de receptor de notificación.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del tipo de receptor de notificación.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del tipo de receptor de notificación.");

                    b.HasKey("Id");

                    b.ToTable("tipo_receptor_notificacion", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los tipos de receptores de notificación.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoUnidadTiempo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del tipo de unidad de tiempo.");

                    b.Property<long>("CantSegundos")
                        .HasColumnType("bigint")
                        .HasColumnName("cant_segundos")
                        .HasComment("Cantidad de segundos que representan a la unidad de tiempo.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del tipo de unidad de tiempo.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del tipo de unidad de tiempo.");

                    b.HasKey("Id");

                    b.ToTable("tipo_unidad_tiempo", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los tipos de unidades de tiempo.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.DestinatarioNotificacion", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.TipoReceptorNotificacion", "TipoReceptorNotificacion")
                        .WithMany("DestinatariosNotificaciones")
                        .HasForeignKey("IdTipoReceptor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoReceptorNotificacion");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoReceptorNotificacion", b =>
                {
                    b.Navigation("DestinatariosNotificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
