// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TanatosAPI.Entities.Contexts;

#nullable disable

namespace TanatosAPI.Migrations
{
    [DbContext(typeof(TanatosDbContext))]
    [Migration("20260225000603_ColumnHermesIdMensajeEnMensaje")]
    partial class ColumnHermesIdMensajeEnMensaje
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TanatosAPI.Entities.Models.CategoriaNorma", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador de la categoría.");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion")
                        .HasComment("Descripción de la categoría.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre de la categoría.");

                    b.Property<string>("NombreCorto")
                        .HasColumnType("text")
                        .HasColumnName("nombre_corto")
                        .HasComment("Nombre corto de la categoría.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia de la categoría.");

                    b.HasKey("Id");

                    b.ToTable("categoria_norma", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene las categorías de las normas");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.DestinatarioNotificacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del destinatario de notificación.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoValidacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_validacion")
                        .HasComment("Código generado para validar que el destinatario se suscribe a la notificación.");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destino")
                        .HasComment("Destino de la notificación. Puede ser un correo o un número de Whatsapp.");

                    b.Property<DateTime>("FechaCaducidadCodigoValidacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_caducidad_codigo_validacion")
                        .HasDefaultValueSql("NOW() + INTERVAL '24 hours'")
                        .HasComment("Fecha en que caduca el código de validación.");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasComment("Fecha en que se creó el destinatario.");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion")
                        .HasComment("Fecha en que se eliminó el destinatario.");

                    b.Property<DateTime?>("FechaValidacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_validacion")
                        .HasComment("Fecha en que se validó el destinatario.");

                    b.Property<long>("IdNegocio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_negocio")
                        .HasComment("Identificador del negocio del usuario.");

                    b.Property<long>("IdTipoReceptor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_receptor")
                        .HasComment("Identificador del tipo de receptor asociado al destinatario.");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub")
                        .HasComment("Usuario al que pertenece el destinatario de notificación.");

                    b.Property<bool>("Validado")
                        .HasColumnType("boolean")
                        .HasColumnName("validado")
                        .HasComment("Identifica si el destinatario ya fue validado.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del destinatario.");

                    b.HasKey("Id");

                    b.HasIndex("CodigoValidacion")
                        .IsUnique();

                    b.HasIndex("IdNegocio");

                    b.HasIndex("IdTipoReceptor");

                    b.HasIndex("Sub", "IdNegocio", "IdTipoReceptor");

                    b.ToTable("destinatario_notificacion", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los destinatarios de las notificaciones de un usuario.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.DocumentoAdjunto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del documento adjunto.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BucketKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bucket_key")
                        .HasComment("Identificador del objeto dentro del bucket.");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bucket_name")
                        .HasComment("Nombre del bucket donde está almacenado el documento.");

                    b.Property<short>("EstadoSubida")
                        .HasColumnType("smallint")
                        .HasColumnName("estado_subida")
                        .HasComment("Estado de subida del documento adjunto. 0: Generada URL prefirmada para PUT - 1: Documento recepcionado.");

                    b.Property<DateTime?>("FechaConfirmacionSubida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_confirmacion_subida")
                        .HasComment("Fecha en que se confirmó la subida del archivo.");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasComment("Fecha en que se creó el registro.");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion")
                        .HasComment("Fecha en que se eliminó el registro.");

                    b.Property<DateTime>("FechaEmisionUrlPrefirmadaPut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision_url_prefirmada_put")
                        .HasComment("Fecha en que se emitió la URL prefirmada para método PUT.");

                    b.Property<long>("IdHistorialNormaSuscrita")
                        .HasColumnType("bigint")
                        .HasColumnName("id_historial_norma_suscrita")
                        .HasComment("Identificador del historial de ejecución de una norma suscrita.");

                    b.Property<string>("MimeEsperado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_esperado")
                        .HasComment("Mime esperado del archivo.");

                    b.Property<string>("MimeReal")
                        .HasColumnType("text")
                        .HasColumnName("mime_real")
                        .HasComment("Mime real del archivo.");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_archivo")
                        .HasComment("Nombre original del archivo.");

                    b.Property<long>("TamannoEsperado")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanno_esperado")
                        .HasComment("Tamaño esperado del archivo en bytes.");

                    b.Property<long?>("TamannoReal")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanno_real")
                        .HasComment("Tamaño real del archivo en bytes.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del registro.");

                    b.HasKey("Id");

                    b.HasIndex("IdHistorialNormaSuscrita");

                    b.HasIndex("BucketName", "BucketKey");

                    b.ToTable("documento_adjunto", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene la metadata de los documentos adjuntos asociados al historial de ejecución de una norma suscrita.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.FiscalizadorNormaSuscrita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del fiscalizador asociado a una norma suscrita.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasComment("Fecha en que se creó al fiscalizador asociado.");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion")
                        .HasComment("Fecha en que se eliminó al fiscalizador asociado.");

                    b.Property<long>("IdNormaSuscrita")
                        .HasColumnType("bigint")
                        .HasColumnName("id_norma_suscrita")
                        .HasComment("Identificador de la norma suscrita.");

                    b.Property<long>("IdTipoFiscalizador")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_fiscalizador")
                        .HasComment("Identificador del fiscalizador asociado.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del fiscalizador asociado.");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoFiscalizador");

                    b.HasIndex("IdNormaSuscrita", "Vigencia");

                    b.ToTable("fiscalizador_norma_suscrita", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los fiscalizadores asociados a una norma suscrita.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.HistorialNormaSuscrita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del historial de ejecución de una norma suscrita.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("FechaCompletitud")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_completitud")
                        .HasComment("Fecha en que se completó la ejecución de la norma suscrita.");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasComment("Fecha en que se creó el registro.");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion")
                        .HasComment("Fecha en que se eliminó el registro.");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento")
                        .HasComment("Fecha en que vencerá la ejecución de la norma suscrita");

                    b.Property<long>("IdNormaSuscrita")
                        .HasColumnType("bigint")
                        .HasColumnName("id_norma_suscrita")
                        .HasComment("Identificador de la norma suscrita.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del registro.");

                    b.HasKey("Id");

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("IdNormaSuscrita", "FechaVencimiento");

                    b.ToTable("historial_norma_suscrita", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene el historial de ejecución de una norma suscrita.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.HistorialNotificacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del historial de notificación de una norma suscrita.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CantAntelacion")
                        .HasColumnType("integer")
                        .HasColumnName("cant_antelacion")
                        .HasComment("Cantidad de unidades de tiempo correspondientes a la notificación.");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasComment("Fecha en que se creó el registro.");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ejecucion")
                        .HasComment("Fecha en que se ejecutó el envío de la notificación.");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion")
                        .HasComment("Fecha en que se eliminó el registro.");

                    b.Property<DateTime>("FechaProgramacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_programacion")
                        .HasComment("Fecha en que se programó el envío de la notificación.");

                    b.Property<string>("HermesIdMensaje")
                        .HasColumnType("text")
                        .HasColumnName("hermes_id_mensaje")
                        .HasComment("ID del mensaje en Hermes.");

                    b.Property<long>("IdDestinatarioNotificacion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_destinatario_notificacion")
                        .HasComment("Identificador del destinatario de la notificación.");

                    b.Property<long>("IdHistorialNormaSuscrita")
                        .HasColumnType("bigint")
                        .HasColumnName("id_historial_norma_suscrita")
                        .HasComment("Identificador del historial de ejecución de una norma suscrita.");

                    b.Property<long?>("IdTipoUnidadTiempoAntelacion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_unidad_tiempo_antelacion")
                        .HasComment("Identificador del tipo de unidad de tiempo correspondiente a la notificación.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del registro.");

                    b.HasKey("Id");

                    b.HasIndex("IdDestinatarioNotificacion");

                    b.HasIndex("IdHistorialNormaSuscrita");

                    b.ToTable("historial_notificacion", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene el historial de notificaciones de una norma suscrita.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.InscripcionTemplate", b =>
                {
                    b.Property<string>("Sub")
                        .HasColumnType("text")
                        .HasColumnName("sub")
                        .HasComment("Usuario al que está asociada la inscripción.");

                    b.Property<long>("IdNegocio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_negocio")
                        .HasComment("Identificador del negocio del usuario.");

                    b.Property<long>("IdTemplate")
                        .HasColumnType("bigint")
                        .HasColumnName("id_template")
                        .HasComment("Identificador del template al que está inscrito el usuario.");

                    b.Property<DateTime>("FechaActivacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_activacion")
                        .HasComment("Fecha en que se activa la inscripción.");

                    b.Property<DateTime?>("FechaDesactivacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_desactivacion")
                        .HasComment("Fecha en que se desactiva la inscripción.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia de la inscripción.");

                    b.HasKey("Sub", "IdNegocio", "IdTemplate");

                    b.HasIndex("IdNegocio");

                    b.HasIndex("IdTemplate");

                    b.ToTable("inscripcion_template", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los templates a los que un usuario está inscrito.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.Mensaje", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador de la notificación asociada a una norma suscrita.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido")
                        .HasComment("Contenido del mensaje.");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo")
                        .HasComment("Correo electrónico del usuario que ingresó el mensaje.");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasComment("Fecha en que se creó el mensaje.");

                    b.Property<string>("HermesIdMensaje")
                        .HasColumnType("text")
                        .HasColumnName("hermes_id_mensaje")
                        .HasComment("ID del mensaje en Hermes.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del usuario que ingresó el mensaje.");

                    b.Property<string>("Sub")
                        .HasColumnType("text")
                        .HasColumnName("sub")
                        .HasComment("Usuario que ingresó el mensaje.");

                    b.HasKey("Id");

                    b.HasIndex("Correo");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("Sub");

                    b.ToTable("mensaje", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los mensajes ingresados por formulario de contacto.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.Negocio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del negocio.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion")
                        .HasComment("Dirección del negocio.");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasComment("Fecha en que se creó el negocio.");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion")
                        .HasComment("Fecha en que se eliminó el negocio.");

                    b.Property<long?>("IdTipoActividad")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_actividad")
                        .HasComment("Identificador de la actividad que efectúa el negocio.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del negocio.");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub")
                        .HasComment("Usuario al que pertenece el negocio.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del negocio.");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoActividad");

                    b.HasIndex("Sub", "Nombre");

                    b.ToTable("negocio", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los negocios de un usuario.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.NormaSuscrita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador de la norma suscrita.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado")
                        .HasComment("Estado de activación de la norma.");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion")
                        .HasComment("Descripcion de la norma.");

                    b.Property<bool>("Editable")
                        .HasColumnType("boolean")
                        .HasColumnName("editable")
                        .HasComment("Indicador de si es editable la norma.");

                    b.Property<DateTime?>("FechaActivacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_activacion")
                        .HasComment("Fecha en que se activó el cumplimiento de la norma.");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasComment("Fecha en que se creó la norma.");

                    b.Property<DateTime?>("FechaDesactivacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_desactivacion")
                        .HasComment("Fecha en que se desactivó el cumplimiento de la norma.");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion")
                        .HasComment("Fecha en que se eliminó la norma.");

                    b.Property<long?>("IdCategoriaNorma")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria_norma")
                        .HasComment("Identificador de la categoría a la que pertenece la norma.");

                    b.Property<long>("IdNegocio")
                        .HasColumnType("bigint")
                        .HasColumnName("id_negocio")
                        .HasComment("Identificador del negocio del usuario.");

                    b.Property<long?>("IdNorma")
                        .HasColumnType("bigint")
                        .HasColumnName("id_norma")
                        .HasComment("Identificador del template norma al que pertenece la norma suscrita.");

                    b.Property<long?>("IdTemplate")
                        .HasColumnType("bigint")
                        .HasColumnName("id_template")
                        .HasComment("Identificador del template al que pertenece la norma suscrita.");

                    b.Property<long?>("IdTipoPeriodicidad")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_periodicidad")
                        .HasComment("Identificador del tipo de periodicidad asociado a la norma.");

                    b.Property<string>("Multa")
                        .HasColumnType("text")
                        .HasColumnName("multa")
                        .HasComment("Multa de no cumplir con la norma.");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre de la norma.");

                    b.Property<long?>("OrdenVisual")
                        .HasColumnType("bigint")
                        .HasColumnName("orden_visual")
                        .HasComment("Orden en que se deben presentar las normas.");

                    b.Property<List<Dictionary<string, JsonElement>>>("ProcesosNotificaciones")
                        .HasColumnType("jsonb")
                        .HasColumnName("procesos_notificaciones")
                        .HasComment("Procesos de notificaciones asociados a la norma suscrita.");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub")
                        .HasComment("Usuario al que pertenece la norma suscrita.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia de la norma.");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoriaNorma");

                    b.HasIndex("IdNegocio");

                    b.HasIndex("IdTipoPeriodicidad");

                    b.HasIndex("IdTemplate", "IdNorma");

                    b.HasIndex("Sub", "IdNegocio");

                    b.ToTable("norma_suscrita", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene las normas a las que está suscrita un negocio del usuario.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.NotificacionNormaSuscrita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador de la notificación asociada a una norma suscrita.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CantAntelacion")
                        .HasColumnType("integer")
                        .HasColumnName("cant_antelacion")
                        .HasComment("Cantidad de unidades de tiempo a usar para la notificación.");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasComment("Fecha en que se creó la notificación asociada.");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion")
                        .HasComment("Fecha en que se eliminó la notificación asociada.");

                    b.Property<long>("IdNormaSuscrita")
                        .HasColumnType("bigint")
                        .HasColumnName("id_norma_suscrita")
                        .HasComment("Identificador de la norma suscrita.");

                    b.Property<long>("IdTipoUnidadTiempoAntelacion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_unidad_tiempo_antelacion")
                        .HasComment("Identificador del tipo de unidad de tiempo a usar para la notificación.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia de la notificación asociada.");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoUnidadTiempoAntelacion");

                    b.HasIndex("IdNormaSuscrita", "Vigencia");

                    b.ToTable("notificacion_norma_suscrita", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene las notificaciones asociados a una norma suscrita.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.Template", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del template.");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion")
                        .HasComment("Descripcion del template.");

                    b.Property<long?>("IdTemplatePadre")
                        .HasColumnType("bigint")
                        .HasColumnName("id_template_padre")
                        .HasComment("Identificador del template padre.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del template.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del template.");

                    b.HasKey("Id");

                    b.HasIndex("IdTemplatePadre");

                    b.ToTable("template", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los templates de normas a inscribirse.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateActividad", b =>
                {
                    b.Property<long>("IdTemplate")
                        .HasColumnType("bigint")
                        .HasColumnName("id_template")
                        .HasComment("Identificador del template.");

                    b.Property<long>("IdTipoActividad")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_actividad")
                        .HasComment("Identificador del tipo de actividad del negocio.");

                    b.HasKey("IdTemplate", "IdTipoActividad");

                    b.HasIndex("IdTipoActividad");

                    b.ToTable("template_actividad", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene la recomendación de templates según tipo de actividad de un negocio.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNorma", b =>
                {
                    b.Property<long>("IdTemplate")
                        .HasColumnType("bigint")
                        .HasColumnName("id_template")
                        .HasComment("Identificador del template al que pertenece la norma.");

                    b.Property<long>("IdNorma")
                        .HasColumnType("bigint")
                        .HasColumnName("id_norma")
                        .HasComment("Identificador de la norma asociada al template.");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion")
                        .HasComment("Descripcion de la norma.");

                    b.Property<long>("IdCategoriaNorma")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria_norma")
                        .HasComment("Identificador de la categoría a la que pertenece la norma.");

                    b.Property<long?>("IdTipoPeriodicidad")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_periodicidad")
                        .HasComment("Identificador del tipo de periodicidad asociado a la norma.");

                    b.Property<string>("Multa")
                        .HasColumnType("text")
                        .HasColumnName("multa")
                        .HasComment("Multa de no cumplir con la norma");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre de la norma.");

                    b.HasKey("IdTemplate", "IdNorma");

                    b.HasIndex("IdCategoriaNorma");

                    b.HasIndex("IdTipoPeriodicidad");

                    b.ToTable("template_norma", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene las normas asociadas a un template.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNormaFiscalizador", b =>
                {
                    b.Property<long>("IdTemplate")
                        .HasColumnType("bigint")
                        .HasColumnName("id_template")
                        .HasComment("Identificador del template al que pertenece la norma.");

                    b.Property<long>("IdNorma")
                        .HasColumnType("bigint")
                        .HasColumnName("id_norma")
                        .HasComment("Identificador de la norma asociada al template.");

                    b.Property<long>("IdTipoFiscalizador")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_fiscalizador")
                        .HasComment("Identificador del tipo de fiscalizador.");

                    b.HasKey("IdTemplate", "IdNorma", "IdTipoFiscalizador");

                    b.HasIndex("IdTipoFiscalizador");

                    b.ToTable("template_norma_fiscalizador", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene la relación entre un template norma y un fiscalizador.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNormaNotificacion", b =>
                {
                    b.Property<long>("IdTemplate")
                        .HasColumnType("bigint")
                        .HasColumnName("id_template")
                        .HasComment("Identificador del template al que pertenece la norma.");

                    b.Property<long>("IdNorma")
                        .HasColumnType("bigint")
                        .HasColumnName("id_norma")
                        .HasComment("Identificador de la norma asociada al template.");

                    b.Property<long>("IdTipoUnidadTiempoAntelacion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_unidad_tiempo_antelacion")
                        .HasComment("Identificador del tipo de unidad de tiempo a usar para la notificación.");

                    b.Property<int>("CantAntelacion")
                        .HasColumnType("integer")
                        .HasColumnName("cant_antelacion")
                        .HasComment("Cantidad de unidades de tiempo a usar para la notificación.");

                    b.HasKey("IdTemplate", "IdNorma", "IdTipoUnidadTiempoAntelacion", "CantAntelacion");

                    b.HasIndex("IdTipoUnidadTiempoAntelacion");

                    b.ToTable("template_norma_notificacion", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene las notificaciones asociadas a una template norma.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoActividad", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador de la actividad.");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion")
                        .HasComment("Descripción de la actividad.");

                    b.Property<long>("IdTipoRubro")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_rubro")
                        .HasComment("Identificador del rubro al que pertenece la actividad.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre de la actividad.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia de la actividad.");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoRubro");

                    b.ToTable("tipo_actividad", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene las actividades que puede hacer un negocio.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoFiscalizador", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del tipo de fiscalizador.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del tipo de fiscalizador.");

                    b.Property<string>("NombreCorto")
                        .HasColumnType("text")
                        .HasColumnName("nombre_corto")
                        .HasComment("Nombre corto del tipo de fiscalizador.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del tipo de fiscalizador.");

                    b.HasKey("Id");

                    b.ToTable("tipo_fiscalizador", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los tipos de fiscalizadores de las normas.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoPeriodicidad", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del tipo de periodicidad.");

                    b.Property<string>("Cron")
                        .HasColumnType("text")
                        .HasColumnName("cron")
                        .HasComment("Cron del tipo de periodicidad.");

                    b.Property<int?>("DeltaAnnos")
                        .HasColumnType("integer")
                        .HasColumnName("delta_annos")
                        .HasComment("Delta en años de la periodicidad.");

                    b.Property<int?>("DeltaDias")
                        .HasColumnType("integer")
                        .HasColumnName("delta_dias")
                        .HasComment("Delta en días de la periodicidad.");

                    b.Property<int?>("DeltaMeses")
                        .HasColumnType("integer")
                        .HasColumnName("delta_meses")
                        .HasComment("Delta en meses de la periodicidad.");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion")
                        .HasComment("Descripción del tipo de periodicidad.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del tipo de periodicidad.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del tipo de periodicidad.");

                    b.HasKey("Id");

                    b.ToTable("tipo_periodicidad", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los tipos de periodicidad.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoReceptorNotificacion", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del tipo de receptor de notificación.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del tipo de receptor de notificación.");

                    b.Property<string>("RegexValidacion")
                        .HasColumnType("text")
                        .HasColumnName("regex_validacion")
                        .HasComment("Regex para validar el tipo de receptor.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del tipo de receptor de notificación.");

                    b.HasKey("Id");

                    b.ToTable("tipo_receptor_notificacion", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los tipos de receptores de notificación.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoRubro", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del rubro.");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion")
                        .HasComment("Descripción del rubro.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del rubro.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del rubro.");

                    b.HasKey("Id");

                    b.ToTable("tipo_rubro", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los rubros a los que puede pertenecer un negocio.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoUnidadTiempo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Identificador del tipo de unidad de tiempo.");

                    b.Property<long>("CantSegundos")
                        .HasColumnType("bigint")
                        .HasColumnName("cant_segundos")
                        .HasComment("Cantidad de segundos que representan a la unidad de tiempo.");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasComment("Nombre del tipo de unidad de tiempo.");

                    b.Property<string>("NombrePlural")
                        .HasColumnType("text")
                        .HasColumnName("nombre_plural")
                        .HasComment("Nombre plural del tipo de unidad de tiempo.");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("boolean")
                        .HasColumnName("vigencia")
                        .HasComment("Vigencia del tipo de unidad de tiempo.");

                    b.HasKey("Id");

                    b.ToTable("tipo_unidad_tiempo", "tanatos", t =>
                        {
                            t.HasComment("Tabla que contiene los tipos de unidades de tiempo.");
                        });
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.DestinatarioNotificacion", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.Negocio", "Negocio")
                        .WithMany("DestinatariosNotificaciones")
                        .HasForeignKey("IdNegocio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.TipoReceptorNotificacion", "TipoReceptorNotificacion")
                        .WithMany("DestinatariosNotificaciones")
                        .HasForeignKey("IdTipoReceptor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");

                    b.Navigation("TipoReceptorNotificacion");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.DocumentoAdjunto", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.HistorialNormaSuscrita", "HistorialNormaSuscrita")
                        .WithMany("DocumentosAdjuntos")
                        .HasForeignKey("IdHistorialNormaSuscrita")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HistorialNormaSuscrita");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.FiscalizadorNormaSuscrita", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.NormaSuscrita", "NormaSuscrita")
                        .WithMany("FiscalizadoresNormaSuscrita")
                        .HasForeignKey("IdNormaSuscrita")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.TipoFiscalizador", "TipoFiscalizador")
                        .WithMany("FiscalizadoresNormaSuscrita")
                        .HasForeignKey("IdTipoFiscalizador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NormaSuscrita");

                    b.Navigation("TipoFiscalizador");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.HistorialNormaSuscrita", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.NormaSuscrita", "NormaSuscrita")
                        .WithMany("HistorialesNormaSuscrita")
                        .HasForeignKey("IdNormaSuscrita")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NormaSuscrita");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.HistorialNotificacion", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.DestinatarioNotificacion", "DestinatarioNotificacion")
                        .WithMany("HistorialNotificaciones")
                        .HasForeignKey("IdDestinatarioNotificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.HistorialNormaSuscrita", "HistorialNormaSuscrita")
                        .WithMany("HistorialNotificaciones")
                        .HasForeignKey("IdHistorialNormaSuscrita")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinatarioNotificacion");

                    b.Navigation("HistorialNormaSuscrita");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.InscripcionTemplate", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.Negocio", "Negocio")
                        .WithMany("InscripcionesTemplates")
                        .HasForeignKey("IdNegocio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.Template", "Template")
                        .WithMany("InscripcionesTemplate")
                        .HasForeignKey("IdTemplate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.Negocio", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.TipoActividad", "TipoActividad")
                        .WithMany("Negocios")
                        .HasForeignKey("IdTipoActividad")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoActividad");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.NormaSuscrita", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.CategoriaNorma", "CategoriaNorma")
                        .WithMany("NormasSuscritas")
                        .HasForeignKey("IdCategoriaNorma")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TanatosAPI.Entities.Models.Negocio", "Negocio")
                        .WithMany("NormasSuscritas")
                        .HasForeignKey("IdNegocio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.TipoPeriodicidad", "TipoPeriodicidad")
                        .WithMany("NormasSuscritas")
                        .HasForeignKey("IdTipoPeriodicidad")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TanatosAPI.Entities.Models.TemplateNorma", "TemplateNorma")
                        .WithMany("NormasSuscritas")
                        .HasForeignKey("IdTemplate", "IdNorma")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaNorma");

                    b.Navigation("Negocio");

                    b.Navigation("TemplateNorma");

                    b.Navigation("TipoPeriodicidad");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.NotificacionNormaSuscrita", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.NormaSuscrita", "NormaSuscrita")
                        .WithMany("NotificacionesNormaSuscrita")
                        .HasForeignKey("IdNormaSuscrita")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.TipoUnidadTiempo", "TipoUnidadTiempo")
                        .WithMany("NotificacionesNormaSuscrita")
                        .HasForeignKey("IdTipoUnidadTiempoAntelacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NormaSuscrita");

                    b.Navigation("TipoUnidadTiempo");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.Template", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.Template", "TemplatePadre")
                        .WithMany("TemplatesHijos")
                        .HasForeignKey("IdTemplatePadre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TemplatePadre");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateActividad", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.Template", "Template")
                        .WithMany("TemplateActividades")
                        .HasForeignKey("IdTemplate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.TipoActividad", "TipoActividad")
                        .WithMany("TemplatesActividad")
                        .HasForeignKey("IdTipoActividad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("TipoActividad");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNorma", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.CategoriaNorma", "CategoriaNorma")
                        .WithMany("TemplateNormas")
                        .HasForeignKey("IdCategoriaNorma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.Template", "Template")
                        .WithMany("TemplateNormas")
                        .HasForeignKey("IdTemplate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.TipoPeriodicidad", "TipoPeriodicidad")
                        .WithMany("TemplateNormas")
                        .HasForeignKey("IdTipoPeriodicidad")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaNorma");

                    b.Navigation("Template");

                    b.Navigation("TipoPeriodicidad");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNormaFiscalizador", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.TipoFiscalizador", "TipoFiscalizador")
                        .WithMany("TemplateNormasFiscalizador")
                        .HasForeignKey("IdTipoFiscalizador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.TemplateNorma", "TemplateNorma")
                        .WithMany("TemplateNormaFiscalizadores")
                        .HasForeignKey("IdTemplate", "IdNorma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TemplateNorma");

                    b.Navigation("TipoFiscalizador");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNormaNotificacion", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.TipoUnidadTiempo", "TipoUnidadTiempoAntelacion")
                        .WithMany("TemplateNormasNotificacion")
                        .HasForeignKey("IdTipoUnidadTiempoAntelacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TanatosAPI.Entities.Models.TemplateNorma", "TemplateNorma")
                        .WithMany("TemplateNormaNotificaciones")
                        .HasForeignKey("IdTemplate", "IdNorma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TemplateNorma");

                    b.Navigation("TipoUnidadTiempoAntelacion");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoActividad", b =>
                {
                    b.HasOne("TanatosAPI.Entities.Models.TipoRubro", "TipoRubro")
                        .WithMany("TiposActividades")
                        .HasForeignKey("IdTipoRubro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoRubro");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.CategoriaNorma", b =>
                {
                    b.Navigation("NormasSuscritas");

                    b.Navigation("TemplateNormas");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.DestinatarioNotificacion", b =>
                {
                    b.Navigation("HistorialNotificaciones");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.HistorialNormaSuscrita", b =>
                {
                    b.Navigation("DocumentosAdjuntos");

                    b.Navigation("HistorialNotificaciones");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.Negocio", b =>
                {
                    b.Navigation("DestinatariosNotificaciones");

                    b.Navigation("InscripcionesTemplates");

                    b.Navigation("NormasSuscritas");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.NormaSuscrita", b =>
                {
                    b.Navigation("FiscalizadoresNormaSuscrita");

                    b.Navigation("HistorialesNormaSuscrita");

                    b.Navigation("NotificacionesNormaSuscrita");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.Template", b =>
                {
                    b.Navigation("InscripcionesTemplate");

                    b.Navigation("TemplateActividades");

                    b.Navigation("TemplateNormas");

                    b.Navigation("TemplatesHijos");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TemplateNorma", b =>
                {
                    b.Navigation("NormasSuscritas");

                    b.Navigation("TemplateNormaFiscalizadores");

                    b.Navigation("TemplateNormaNotificaciones");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoActividad", b =>
                {
                    b.Navigation("Negocios");

                    b.Navigation("TemplatesActividad");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoFiscalizador", b =>
                {
                    b.Navigation("FiscalizadoresNormaSuscrita");

                    b.Navigation("TemplateNormasFiscalizador");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoPeriodicidad", b =>
                {
                    b.Navigation("NormasSuscritas");

                    b.Navigation("TemplateNormas");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoReceptorNotificacion", b =>
                {
                    b.Navigation("DestinatariosNotificaciones");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoRubro", b =>
                {
                    b.Navigation("TiposActividades");
                });

            modelBuilder.Entity("TanatosAPI.Entities.Models.TipoUnidadTiempo", b =>
                {
                    b.Navigation("NotificacionesNormaSuscrita");

                    b.Navigation("TemplateNormasNotificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
