FROM public.ecr.aws/amazonlinux/amazonlinux:2023

LABEL org.opencontainers.image.description="Builder image para publish AOT en AWS Lambda - SDK .NET con Toolchain Nativo"

RUN yum install -y dotnet-sdk-10.0 gcc zlib-devel zip \
    && yum clean all \
    && rm -rf /var/cache/yum