// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TanatosAPI.Entities.CompiledModels
{
    public partial class TanatosDbContextModel
    {
        private TanatosDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("78751406-757c-4de5-9e19-7f336e80e516"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var tipoReceptorNotificacion = TipoReceptorNotificacionEntityType.Create(this);

            TipoReceptorNotificacionEntityType.CreateAnnotations(tipoReceptorNotificacion);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.11");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var tipoReceptorNotificacion = FindEntityType("TanatosAPI.Entities.Models.TipoReceptorNotificacion")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            tipoReceptorNotificacion.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var tanatosAPIEntitiesModelsTipoReceptorNotificacionTableBase = new TableBase("TanatosAPI.Entities.Models.TipoReceptorNotificacion", null, relationalModel);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("id", "bigint", tanatosAPIEntitiesModelsTipoReceptorNotificacionTableBase);
            tanatosAPIEntitiesModelsTipoReceptorNotificacionTableBase.Columns.Add("id", idColumnBase);
            var nombreColumnBase = new ColumnBase<ColumnMappingBase>("nombre", "text", tanatosAPIEntitiesModelsTipoReceptorNotificacionTableBase);
            tanatosAPIEntitiesModelsTipoReceptorNotificacionTableBase.Columns.Add("nombre", nombreColumnBase);
            var vigenteColumnBase = new ColumnBase<ColumnMappingBase>("vigente", "boolean", tanatosAPIEntitiesModelsTipoReceptorNotificacionTableBase);
            tanatosAPIEntitiesModelsTipoReceptorNotificacionTableBase.Columns.Add("vigente", vigenteColumnBase);
            relationalModel.DefaultTables.Add("TanatosAPI.Entities.Models.TipoReceptorNotificacion", tanatosAPIEntitiesModelsTipoReceptorNotificacionTableBase);
            var tanatosAPIEntitiesModelsTipoReceptorNotificacionMappingBase = new TableMappingBase<ColumnMappingBase>(tipoReceptorNotificacion, tanatosAPIEntitiesModelsTipoReceptorNotificacionTableBase, null);
            tanatosAPIEntitiesModelsTipoReceptorNotificacionTableBase.AddTypeMapping(tanatosAPIEntitiesModelsTipoReceptorNotificacionMappingBase, false);
            defaultTableMappings.Add(tanatosAPIEntitiesModelsTipoReceptorNotificacionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, tipoReceptorNotificacion.FindProperty("Id")!, tanatosAPIEntitiesModelsTipoReceptorNotificacionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nombreColumnBase, tipoReceptorNotificacion.FindProperty("Nombre")!, tanatosAPIEntitiesModelsTipoReceptorNotificacionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)vigenteColumnBase, tipoReceptorNotificacion.FindProperty("Vigente")!, tanatosAPIEntitiesModelsTipoReceptorNotificacionMappingBase);

            var tableMappings = new List<TableMapping>();
            tipoReceptorNotificacion.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var tipo_receptor_notificacionTable = new Table("tipo_receptor_notificacion", "tanatos", relationalModel);
            var idColumn = new Column("id", "bigint", tipo_receptor_notificacionTable);
            tipo_receptor_notificacionTable.Columns.Add("id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(idColumn);
            var nombreColumn = new Column("nombre", "text", tipo_receptor_notificacionTable);
            tipo_receptor_notificacionTable.Columns.Add("nombre", nombreColumn);
            nombreColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nombreColumn);
            var vigenteColumn = new Column("vigente", "boolean", tipo_receptor_notificacionTable);
            tipo_receptor_notificacionTable.Columns.Add("vigente", vigenteColumn);
            vigenteColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(vigenteColumn);
            relationalModel.Tables.Add(("tipo_receptor_notificacion", "tanatos"), tipo_receptor_notificacionTable);
            var tipo_receptor_notificacionTableMapping = new TableMapping(tipoReceptorNotificacion, tipo_receptor_notificacionTable, null);
            tipo_receptor_notificacionTable.AddTypeMapping(tipo_receptor_notificacionTableMapping, false);
            tableMappings.Add(tipo_receptor_notificacionTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, tipoReceptorNotificacion.FindProperty("Id")!, tipo_receptor_notificacionTableMapping);
            RelationalModel.CreateColumnMapping(nombreColumn, tipoReceptorNotificacion.FindProperty("Nombre")!, tipo_receptor_notificacionTableMapping);
            RelationalModel.CreateColumnMapping(vigenteColumn, tipoReceptorNotificacion.FindProperty("Vigente")!, tipo_receptor_notificacionTableMapping);
            var pK_tipo_receptor_notificacion = new UniqueConstraint("PK_tipo_receptor_notificacion", tipo_receptor_notificacionTable, new[] { idColumn });
            tipo_receptor_notificacionTable.PrimaryKey = pK_tipo_receptor_notificacion;
            pK_tipo_receptor_notificacion.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<long>(pK_tipo_receptor_notificacion));
            var pK_tipo_receptor_notificacionKey = RelationalModel.GetKey(this,
                "TanatosAPI.Entities.Models.TipoReceptorNotificacion",
                new[] { "Id" });
            pK_tipo_receptor_notificacion.MappedKeys.Add(pK_tipo_receptor_notificacionKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_tipo_receptor_notificacionKey).Add(pK_tipo_receptor_notificacion);
            tipo_receptor_notificacionTable.UniqueConstraints.Add("PK_tipo_receptor_notificacion", pK_tipo_receptor_notificacion);
            return relationalModel.MakeReadOnly();
        }
    }
}
