// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using TanatosAPI.Entities.CompiledModels;
using TanatosAPI.Entities.Contexts;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(TanatosDbContext), typeof(TanatosDbContextModel))]
