// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TanatosAPI.Entities.CompiledModels
{
    public partial class TanatosDbContextModel
    {
        private TanatosDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("4d9e3dc9-e94e-4aea-8023-3bbac992d22b"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var tipoReceptorNotificacion = TipoReceptorNotificacionEntityType.Create(this);

            TipoReceptorNotificacionEntityType.CreateAnnotations(tipoReceptorNotificacion);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.11");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
