// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;
using TanatosAPI.Entities.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TanatosAPI.Entities.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TipoReceptorNotificacionEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "TanatosAPI.Entities.Models.TipoReceptorNotificacion",
                typeof(TipoReceptorNotificacion),
                baseEntityType,
                propertyCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(TipoReceptorNotificacion).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TipoReceptorNotificacion).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.SetGetter(
                long (TipoReceptorNotificacion entity) => TipoReceptorNotificacionUnsafeAccessors.Id(entity),
                bool (TipoReceptorNotificacion entity) => TipoReceptorNotificacionUnsafeAccessors.Id(entity) == 0L,
                long (TipoReceptorNotificacion instance) => TipoReceptorNotificacionUnsafeAccessors.Id(instance),
                bool (TipoReceptorNotificacion instance) => TipoReceptorNotificacionUnsafeAccessors.Id(instance) == 0L);
            id.SetSetter(
                (TipoReceptorNotificacion entity, long value) => TipoReceptorNotificacionUnsafeAccessors.Id(entity) = value);
            id.SetMaterializationSetter(
                (TipoReceptorNotificacion entity, long value) => TipoReceptorNotificacionUnsafeAccessors.Id(entity) = value);
            id.SetAccessors(
                long (InternalEntityEntry entry) => TipoReceptorNotificacionUnsafeAccessors.Id(((TipoReceptorNotificacion)(entry.Entity))),
                long (InternalEntityEntry entry) => TipoReceptorNotificacionUnsafeAccessors.Id(((TipoReceptorNotificacion)(entry.Entity))),
                long (InternalEntityEntry entry) => entry.ReadOriginalValue<long>(id, 0),
                long (InternalEntityEntry entry) => entry.ReadRelationshipSnapshotValue<long>(id, 0),
                object (ValueBuffer valueBuffer) => valueBuffer[0]);
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            id.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<long>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var nombre = runtimeEntityType.AddProperty(
                "Nombre",
                typeof(string),
                propertyInfo: typeof(TipoReceptorNotificacion).GetProperty("Nombre", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TipoReceptorNotificacion).GetField("<Nombre>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            nombre.SetGetter(
                string (TipoReceptorNotificacion entity) => TipoReceptorNotificacionUnsafeAccessors.Nombre(entity),
                bool (TipoReceptorNotificacion entity) => TipoReceptorNotificacionUnsafeAccessors.Nombre(entity) == null,
                string (TipoReceptorNotificacion instance) => TipoReceptorNotificacionUnsafeAccessors.Nombre(instance),
                bool (TipoReceptorNotificacion instance) => TipoReceptorNotificacionUnsafeAccessors.Nombre(instance) == null);
            nombre.SetSetter(
                (TipoReceptorNotificacion entity, string value) => TipoReceptorNotificacionUnsafeAccessors.Nombre(entity) = value);
            nombre.SetMaterializationSetter(
                (TipoReceptorNotificacion entity, string value) => TipoReceptorNotificacionUnsafeAccessors.Nombre(entity) = value);
            nombre.SetAccessors(
                string (InternalEntityEntry entry) => TipoReceptorNotificacionUnsafeAccessors.Nombre(((TipoReceptorNotificacion)(entry.Entity))),
                string (InternalEntityEntry entry) => TipoReceptorNotificacionUnsafeAccessors.Nombre(((TipoReceptorNotificacion)(entry.Entity))),
                string (InternalEntityEntry entry) => entry.ReadOriginalValue<string>(nombre, 1),
                string (InternalEntityEntry entry) => entry.GetCurrentValue<string>(nombre),
                object (ValueBuffer valueBuffer) => valueBuffer[1]);
            nombre.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            nombre.TypeMapping = StringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    dbType: System.Data.DbType.String));
            nombre.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            nombre.AddAnnotation("Relational:ColumnName", "nombre");

            var vigente = runtimeEntityType.AddProperty(
                "Vigente",
                typeof(bool),
                propertyInfo: typeof(TipoReceptorNotificacion).GetProperty("Vigente", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TipoReceptorNotificacion).GetField("<Vigente>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            vigente.SetGetter(
                bool (TipoReceptorNotificacion entity) => TipoReceptorNotificacionUnsafeAccessors.Vigente(entity),
                bool (TipoReceptorNotificacion entity) => TipoReceptorNotificacionUnsafeAccessors.Vigente(entity) == false,
                bool (TipoReceptorNotificacion instance) => TipoReceptorNotificacionUnsafeAccessors.Vigente(instance),
                bool (TipoReceptorNotificacion instance) => TipoReceptorNotificacionUnsafeAccessors.Vigente(instance) == false);
            vigente.SetSetter(
                (TipoReceptorNotificacion entity, bool value) => TipoReceptorNotificacionUnsafeAccessors.Vigente(entity) = value);
            vigente.SetMaterializationSetter(
                (TipoReceptorNotificacion entity, bool value) => TipoReceptorNotificacionUnsafeAccessors.Vigente(entity) = value);
            vigente.SetAccessors(
                bool (InternalEntityEntry entry) => TipoReceptorNotificacionUnsafeAccessors.Vigente(((TipoReceptorNotificacion)(entry.Entity))),
                bool (InternalEntityEntry entry) => TipoReceptorNotificacionUnsafeAccessors.Vigente(((TipoReceptorNotificacion)(entry.Entity))),
                bool (InternalEntityEntry entry) => entry.ReadOriginalValue<bool>(vigente, 2),
                bool (InternalEntityEntry entry) => entry.GetCurrentValue<bool>(vigente),
                object (ValueBuffer valueBuffer) => valueBuffer[2]);
            vigente.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            vigente.TypeMapping = NpgsqlBoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v));
            vigente.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            vigente.AddAnnotation("Relational:ColumnName", "vigente");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var nombre = runtimeEntityType.FindProperty("Nombre");
            var vigente = runtimeEntityType.FindProperty("Vigente");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<long>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<long>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((TipoReceptorNotificacion)(source.Entity));
                    return ((ISnapshot)(new Snapshot<long, string, bool>(((ValueComparer<long>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(id)), (source.GetCurrentValue<string>(nombre) == null ? null : ((ValueComparer<string>)(((IProperty)nombre).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(nombre))), ((ValueComparer<bool>)(((IProperty)vigente).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(vigente)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (InternalEntityEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (InternalEntityEntry source) =>
                {
                    var entity = ((TipoReceptorNotificacion)(source.Entity));
                    return ((ISnapshot)(new Snapshot<long>(((ValueComparer<long>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<long>(id)))));
                });
            runtimeEntityType.Counts = new PropertyCounts(
                propertyCount: 3,
                navigationCount: 0,
                complexPropertyCount: 0,
                originalValueCount: 3,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0);
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "tanatos");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "tipo_receptor_notificacion");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
