// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using TanatosAPI.Entities.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TanatosAPI.Entities.CompiledModels
{
    public static class TipoReceptorNotificacionUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref long Id(TipoReceptorNotificacion @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Nombre>k__BackingField")]
        public static extern ref string Nombre(TipoReceptorNotificacion @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Vigente>k__BackingField")]
        public static extern ref bool Vigente(TipoReceptorNotificacion @this);
    }
}
