using Amazon.Lambda.APIGatewayEvents;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Text.Json.Serialization;
using TanatosAPI.Entities.Models;
using TanatosAPI.Entities.Others;

namespace TanatosAPI.Helpers {
	[JsonSerializable(typeof(APIGatewayHttpApiV2ProxyRequest))]
	[JsonSerializable(typeof(APIGatewayHttpApiV2ProxyResponse))]
	[JsonSerializable(typeof(ProblemDetails))]
    [JsonSerializable(typeof(Dictionary<string, string>))]
	[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
	[JsonSerializable(typeof(List<Dictionary<string, JsonElement>>))]
	[JsonSerializable(typeof(EntHermesCorreoEnviar))]
	[JsonSerializable(typeof(EntHermesWhatsappEnviar))]
	[JsonSerializable(typeof(SalHermesEnviar))]
	[JsonSerializable(typeof(SalHermesWhatsappMedia))]
	[JsonSerializable(typeof(List<SalHermesWhatsappConversacion>))]
	[JsonSerializable(typeof(List<SalHermesWhatsappMensaje>))]
	[JsonSerializable(typeof(EntKairosIngresarProceso))]
	[JsonSerializable(typeof(EntKairosParametrosProceso))]
	[JsonSerializable(typeof(SalKairosIngresarProceso))]
	[JsonSerializable(typeof(EntAuthObtenerAccessToken))]
	[JsonSerializable(typeof(SalAuthObtenerAccessToken))]
	[JsonSerializable(typeof(SalAuthRefreshAccessToken))]
	[JsonSerializable(typeof(CategoriaNorma))]
	[JsonSerializable(typeof(List<CategoriaNorma>))]
	[JsonSerializable(typeof(DestinatarioNotificacion))]
	[JsonSerializable(typeof(List<DestinatarioNotificacion>))]
	[JsonSerializable(typeof(InscripcionTemplate))]
	[JsonSerializable(typeof(List<InscripcionTemplate>))]
	[JsonSerializable(typeof(Template))]
	[JsonSerializable(typeof(List<Template>))]
	[JsonSerializable(typeof(TemplateNorma))]
	[JsonSerializable(typeof(List<TemplateNorma>))]
	[JsonSerializable(typeof(TemplateNormaFiscalizador))]
	[JsonSerializable(typeof(List<TemplateNormaFiscalizador>))]
	[JsonSerializable(typeof(TemplateNormaNotificacion))]
	[JsonSerializable(typeof(List<TemplateNormaNotificacion>))]
	[JsonSerializable(typeof(TipoFiscalizador))]
	[JsonSerializable(typeof(List<TipoFiscalizador>))]
	[JsonSerializable(typeof(TipoPeriodicidad))]
	[JsonSerializable(typeof(List<TipoPeriodicidad>))]
	[JsonSerializable(typeof(TipoReceptorNotificacion))]
	[JsonSerializable(typeof(List<TipoReceptorNotificacion>))]
	[JsonSerializable(typeof(TipoUnidadTiempo))]
	[JsonSerializable(typeof(List<TipoUnidadTiempo>))]
	[JsonSerializable(typeof(TipoRubro))]
	[JsonSerializable(typeof(List<TipoRubro>))]
	[JsonSerializable(typeof(TipoActividad))]
	[JsonSerializable(typeof(List<TipoActividad>))]
	[JsonSerializable(typeof(EntDestinatarioNotificacionCrear))]
	[JsonSerializable(typeof(SalDestinatarioNotificacion))]
	[JsonSerializable(typeof(List<SalDestinatarioNotificacion>))]
	[JsonSerializable(typeof(EntDestinatarioNotificacionValidar))]
	[JsonSerializable(typeof(EntNegocioCrear))]
	[JsonSerializable(typeof(EntNegocioActualizar))]
	[JsonSerializable(typeof(SalNegocio))]
	[JsonSerializable(typeof(List<SalNegocio>))]
	[JsonSerializable(typeof(EntNormaSuscritaCrear))]
	[JsonSerializable(typeof(EntNormaSuscritaActualizar))]
	[JsonSerializable(typeof(SalNormaSuscrita))]
	[JsonSerializable(typeof(List<SalNormaSuscrita>))]
	[JsonSerializable(typeof(SalInscripcionTemplate))]
	[JsonSerializable(typeof(List<SalInscripcionTemplate>))]
	[JsonSerializable(typeof(EntInscripcionTemplateActivar))]
	[JsonSerializable(typeof(EntInscripcionTemplateDesactivar))]
	[JsonSerializable(typeof(List<SalNormaSuscritaObtenerConVencimiento>))]
	[JsonSerializable(typeof(List<SalDocumentoAdjunto>))]
	[JsonSerializable(typeof(EntDocumentoAdjuntoGenerarUrlSubida))]
	[JsonSerializable(typeof(EntDocumentoAdjuntoGenerarUrlSubidaPorCodigoAcceso))]
	[JsonSerializable(typeof(SalDocumentoAdjuntoGenerarUrlSubida))]
	[JsonSerializable(typeof(EntDocumentoAdjuntoConfirmarSubida))]
	[JsonSerializable(typeof(EntDocumentoAdjuntoConfirmarSubidaPorCodigoAcceso))]
	[JsonSerializable(typeof(EntDocumentoAdjuntoGenerarUrlBajada))]
	[JsonSerializable(typeof(EntDocumentoAdjuntoGenerarUrlBajadaPorCodigoAcceso))]
	[JsonSerializable(typeof(SalDocumentoAdjuntoGenerarUrlBajada))]
	[JsonSerializable(typeof(SalNormaSuscritaObtenerPorIdConVencimiento))]
	[JsonSerializable(typeof(EntNormaSuscritaCompletarNorma))]
	[JsonSerializable(typeof(EntNormaSuscritaCompletarNormaPorCodigoAcceso))]
	[JsonSerializable(typeof(SalNormaSuscritaCompletarNorma))]
	[JsonSerializable(typeof(SalNegocioInformacionUsuario))]
	[JsonSerializable(typeof(EntMensajeIngresar))]
	[JsonSerializable(typeof(EntWhatsappEnviar))]
	[JsonSerializable(typeof(Plan))]
	[JsonSerializable(typeof(List<Plan>))]
	[JsonSerializable(typeof(List<SalPlan>))]
	[JsonSerializable(typeof(EntPlanCrearEditar))]
	[JsonSerializable(typeof(EntSuscripcionCrear))]
	[JsonSerializable(typeof(SalSuscripcionCrear))]
	[JsonSerializable(typeof(EntSuscripcionWebhook))]
	[JsonSerializable(typeof(EntSuscripcionActivarSuscripcionGratuita))]
	[JsonSerializable(typeof(SalFlowUrlToken))]
	[JsonSerializable(typeof(SalFlowPlanCreate))]
	[JsonSerializable(typeof(SalFlowPlanEdit))]
	[JsonSerializable(typeof(SalFlowPlanDelete))]
	[JsonSerializable(typeof(SalFlowCustomerCreate))]
	[JsonSerializable(typeof(SalFlowCustomerGetRegisterStatus))]
	[JsonSerializable(typeof(SalFlowSubscriptionCreate))]
	[JsonSerializable(typeof(SalFlowSubscriptionGet))]
	[JsonSerializable(typeof(SalFlowSubscriptionCancel))]
	[JsonSerializable(typeof(SalFlowPaymentGetStatus))]
	[JsonSerializable(typeof(SalFlowInvoiceGet))]
	[JsonSerializable(typeof(List<SalSuscripcion>))]
    [JsonSerializable(typeof(SalCargo))]
    [JsonSerializable(typeof(List<SalCargo>))]
    [JsonSerializable(typeof(EntCargoCrear))]
    [JsonSerializable(typeof(EntCargoActualizar))]
	[JsonSerializable(typeof(SalEmpleado))]
	[JsonSerializable(typeof(List<SalEmpleado>))]
	[JsonSerializable(typeof(EntEmpleadoCrear))]
	[JsonSerializable(typeof(EntEmpleadoActualizar))]
    [JsonSerializable(typeof(GoogleRecaptchaCredential))]
    [JsonSerializable(typeof(GoogleAssessmentResponse))]
    [JsonSerializable(typeof(GoogleAssessmentParams))]
    [JsonSerializable(typeof(GoogleTokenResponse))]
    internal partial class AppJsonSerializerContext : JsonSerializerContext {
    }
}
